### ISSUE TITLE
Changing the folder name within straight/repos for a package

### ISSUE THREAD

**Issue by dixius99** [radian-software/straight.el#1008]
I decided to try out a new theme: [catppuccin-theme](https://melpa.org/#/catppuccin-theme).

I noticed that the theme is on GitHub at [https://github.com/catppuccin/emacs](https://github.com/catppuccin/emacs), and so installing with `straight` installs into `~/.config/emacs/straight/repos/emacs`

While this isn't a problem for me right now, I was wondering if there is a way to change the `repos` subfolder name to something else, as there is a chance I might try to install another package that also will try to download to the same `repos/emacs` folder.

In the Vim world, using something like [Vim-Plug](https://github.com/junegunn/vim-plug), this is solved using a format like this:

`Plug 'challenger-deep-theme/vim', { 'as': 'challenger-deep' }`

Which installs the package into `plugged/challenger-deep` instead of `plugged/vim`.

I'm sorry if this is covered in the Readme or in an issue. I looked, but not sure I'm even searching for the right thing.

**Comment by progfolio** [comment]
See the documentation on the `:local-repo` recipe keyword:

https://github.com/radian-software/straight.el#the-recipe-format

**Comment by dixius99** [comment]
That's perfect. Thanks so much for pointing me in the right direction. Can't believe I missed it.
