### ISSUE TITLE
Straight *almost* installs evil correctly

### ISSUE THREAD

**Issue by jsilve24** [radian-software/straight.el#1015]
## What's wrong

Something I have not yet been able to identify is going wrong when straight installs evil. It is causing some errors in evil output. The same is not the case when evil is installed with package.el. 

So I ripped apart my config tracking down this problem only to, quite surprisingly, find that it comes down to how straight is installing evil.
I am still going to guess that its something trivial I am overlooking but I have now gotten it to the point I can reproduce the bug with emacs -Q.

I include two very related scripts that are intended to be run with emacs -Q. `evil-debug.el` (which uses package.el to install evil) and `evil-debug-straight.el` (which uses straight.

The correct output for either script should be:

```
const something = {
       }

        const else = {
        }

        const c = 'bar'
        const a = 'hello'
        const b = 'foo'
```

## Steps to reproduce:
1. start emacs -Q
2. open either files
3. M-x eval-buffer
4. Press enter to run the evil-ex command that is prepopulated in the minibuffer. 
5. Look at the new opened buffer "foo" and compare to correct output listed above.

Only the script that installs evil using package.el seems to get the correct result. 

### Version information

* Emacs version: 28.2
* Operating system: Arch Linux

## Scripts
evil-debug.el

```
;; Set up package.el to work with MELPA
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(package-refresh-contents)

;; Download Evil
(unless (package-installed-p 'evil)
  (package-install 'evil))

;; Enable Evil
(require 'evil)
(evil-mode 1)

(setq evil-ex-search-vim-style-regexp t)



(switch-to-buffer "foo")
(insert "const something = {
        a:  'x',
        b:  'x',
        c:  'x',
        d:  'x',
        }

        const else = {
        a: 'x',
        b: 'x',
        c: 'x',
        d: 'x',
        }

        const c = 'bar'
        const a = 'hello'
        const b = 'foo'")

(evil-ex "g/\\{/+1,/\\}/-1d")
```

evil-debug-straight.el
```
;; Set up package.el to work with MELPA
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'evil)
(require 'evil)
(evil-mode 1)

(setq evil-ex-search-vim-style-regexp t)



(switch-to-buffer "foo")
(insert "const something = {
        a:  'x',
        b:  'x',
        c:  'x',
        d:  'x',
        }

        const else = {
        a: 'x',
        b: 'x',
        c: 'x',
        d: 'x',
        }

        const c = 'bar'
        const a = 'hello'
        const b = 'foo'")

(evil-ex "g/\\{/+1,/\\}/-1d")

```

**Comment by progfolio** [comment]
A diff of the two directories produces the following on my machine:

```shell
n@nbook:evil $ diff ./ /tmp/evil-package.el/elpa/evil-20221122.1450/
diff ./evil-autoloads.el /tmp/evil-package.el/elpa/evil-20221122.1450/evil-autoloads.el
7a8,10
> (add-to-list 'load-path (directory-file-name
>                          (or (file-name-directory #$) (car load-path))))
> 
diff ./evil.info /tmp/evil-package.el/elpa/evil-20221122.1450/evil.info
1c1
< This is evil.info, produced by makeinfo version 7.0 from evil.texi.
---
> This is evil.info, produced by makeinfo version 6.7 from evil.texi.
diff ./evil-pkg.el /tmp/evil-package.el/elpa/evil-20221122.1450/evil-pkg.el
1,4c1
< (define-package
<   "evil"
<   "1.15.0"
<   "Extensible Vi layer for Emacs."
---
> (define-package "evil" "20221122.1450" "Extensible Vi layer for Emacs."
7c4,12
<     (cl-lib "0.5")))
---
>     (cl-lib "0.5"))
>   :commit "2e8576188b1d0768fbf92c6bea2fb3fbed9f019f" :maintainer
>   '("Tom Dalziel" . "tom.dalziel@gmail.com")
>   :keywords
>   '("emulation" "vim")
>   :url "https://github.com/emacs-evil/evil")
> ;; Local Variables:
> ;; no-byte-compile: t
> ;; End:
Only in ./: evil-pkg.elc
Only in ./: evil.texi
```

**Comment by progfolio** [comment]
Running your tests on Emacs 29 I get the same output for both.

* package.el:

```
        a:  'x',
        b:  'x',
        c:  'x',
        d:  'x',
        }

        a: 'x',
        b: 'x',
        c: 'x',
        d: 'x',
        }

        const c = 'bar'
        const a = 'hello'
        const b = 'foo'
```

* straight.el:

```
        a:  'x',
        b:  'x',
        c:  'x',
        d:  'x',
        }

        a: 'x',
        b: 'x',
        c: 'x',
        d: 'x',
        }

        const c = 'bar'
        const a = 'hello'
        const b = 'foo'
```

The docstring of `evil-ex-search-vim-style-regexp` suggests your repro cases may be incomplete:

```
 Note that this only affects the search command if
‘evil-search-module’ is set to ’evil-search. The isearch module
always uses plain Emacs regular expressions.
```

However, changing the default value of that variable did not change the output for me.

**Comment by jsilve24** [comment]
hmm interesting. Yes you are correct, that I needed to have added: 
`(evil-select-search-module 'evil-search-module 'evil-search)` althought interstingly that didn't change the results in either case. 
For me I get the correct output from evil when installed with use-package.el.... 

I get exactly the output you show if I use straight. But I get the correct output if I use package.el

**Comment by progfolio** [comment]
> I just saw you are using emacs 29. Could be thats the reason for the difference?

Possibly. You may be able to find the difference by instrumenting the evil-ex call with [edebug](https://www.gnu.org/software/emacs/manual/html_node/elisp/Using-Edebug.html) and stepping through the execution of both.

**Comment by progfolio** [comment]
Looks like this is being addressed upstream.
I'll close for now. Let me know if we need to re-open.
