### ISSUE TITLE
Straight not copying non `.el` files to build directory

### ISSUE THREAD

**Issue by JordanAnthonyKing** [radian-software/straight.el#1018]
Lsp-bridge requires a python script (included in the root of the repo) to work, after installing with straight (Win11 w/ symlinks enabled) lsp-bridge is unable to find the required python script, which it is looking for in the build folder. The script is present in the repo folder.

Is there an option to copy any extra files from the repo folder to the build folder? Are the symlinks not working properly, or is this an unconsidered scenario?

Thanks.

**Comment by progfolio** [comment]
Please see the section on the `:files` recipe keyword:

https://github.com/radian-software/straight.el#the-recipe-format

**Comment by progfolio** [comment]
e.g.

```emacs-lisp
(straight-use-package '(lsp-bridge :files (:defaults "required_script.py") ;;rest of recipe)
```
