### ISSUE TITLE
Need to use sudo to perform package build.

### ISSUE THREAD

**Issue by anoduck** [radian-software/straight.el#1020]
On my system, using OpenBSD, you have to run cargo with sudo in order to access system libraries. This becomes a real hang up when attempting to install Emacs packages that insist on cargo building a package within Emacs. I noticed the extremely helpful recipe in the README:

``` elisp
'`( package :type git :repo "host/repo"
    :pre-build ,(pcase system-type
                  (`berkeley-unix '("gmake"))
                  (_ '("make")))
    :files (:defaults))
```

I was wondering if it could be modified to provide the sudo for all commands during the build process? Or if there was another means of accomplishing this?

I did modify it to have cargo use sudo during the build of the package, but this only addressed part of the problem, as Emacs was unable to create the symbolic links to the copied files to complete the package installation.

```elisp
( ...
:pre-build ,(pcase system-type
       (`berkley-unix '("sudo cargo"))
       (_ '("cargo")))
```

I was able to do this by configuring sudo to not require a password. Any suggestions.

**Comment by progfolio** [comment]
please see: https://github.com/radian-software/straight.el/issues/725

**Comment by anoduck** [comment]
@progfolio Nice to know. Thanks. I somehow managed to rig it to load without compiling. Brilliant project. Thanks for the help.
