### ISSUE TITLE
How to use Straight to get the latest eww?

### ISSUE THREAD

**Issue by WorldsEndless** [radian-software/straight.el#1023]
I want to try eww again instead of w3m for my browsing, not the least reason being because it is still updated and may have fixed some of its blemishes. But when I run a standard `(use-package eww)` no repo is created in my straight directory, presumably because it is built in to emacs with an older version of eww? I see the repo updated at <https://github.com/emacs-mirror/emacs/blob/master/lisp/net/eww.el>, but there is no source link there because it's a blob. How should I instruct Straight to get the latest eww?

**Comment by progfolio** [comment]
You could provide a recipe which clones the Emacs source repository and has a `:files` directive which points to the location of eww (`lisp/net/eww.el`).
However, I don't think this would work out too well as packages developed in Emacs core have an implicit dependency on the version of Emacs. Chances are the features eww requires:

- cl-lib
- mm-url
- puny
- shr
- text-property-search
- thingatpt
- url
- url-queue
- url-file
- xdg

Have been changed in incompatible ways between the master version of Emacs and any stable version.
