### ISSUE TITLE
[Bug] Straight cannot install the elpa package xeft

### ISSUE THREAD

**Issue by wakatara** [radian-software/straight.el#1038]
## What's wrong

Straight seems unable to install xeft, a package on elpa, even after updating recipe repositories. 

## Directions to reproduce

I used the following config: 

``` elisp
(use-package xeft
  :straight t
  :init
  (setq deft-default-extension "org")
  (setq xeft-database "~/.config/emacs")
  (setq xeft-directory "~/Documents/org")
  (setq xeft-recursive t)
  )
```

It gives the following error: 
`error: Could not find package xeft. Updating recipe repositories: (org-elpa melpa gnu-elpa-mirror nongnu-elpa el-get emacsmirror-mirror) with ‘straight-pull-recipe-repositories’ may fix this`

Executing `straight-pull-recipe-repositories` works for updates (it seems - let me know if there is a way to confirm this), but does not allow the package to be found. I get the same error. (use-package can seem to update repos though to have xeft show in elpa.).

(as a side note, trying to install directly from the git source also seems to fail as sourcehut (git.sec.ht) is not recognized as a viable host by straight).

### Version information

* Emacs version: 29.0.60
* Operating system: OSX 13.1

By the way, thanks for all the wonderful work on straight. It's great. Love the fork feature and has allowed me to contribute back to emacs packages with bug fixes easily. ❤️

**Comment by wakatara** [comment]
Interestingly, the module to be compiled is a bit of an issue, mostly because the `Makefile` and `xapian-lite.cc` module need to be in `/build` rather than `/repo` (I symlinked them manually but I guess the next restart of emacs had straight nuke them, I guess? 

The author of xeft actually asked if you could let us know how we might need to modify the source (or signal to straight it needs to copy those files as well) so as to make this easier for folks on macs. 

Btw, thanks for the quick response (and all your amazing work on straight).

**Comment by wakatara** [comment]
Doh... never mind, figured it out myself (someimes it really does help to read the docs... =] ). 

``` elisp

(straight-use-package
 '(xeft :repo "https://git.sr.ht/~casouri/xeft"
        :files  (:defaults "*.h" "Makefile" "xapian-lite.cc")))
```

seems to do the trick. Apologies!

**Comment by raxod502** [comment]
Hmm. Ok, GNU ELPA Mirror probably isn't working properly. I have been working on fixing some problems that were recently reported, and I thought that it had not been broken so long as a month, but I guess that's possible. Either way, the issue should be resolved when I finish fixing https://github.com/radian-software/gnu-elpa-mirror/issues/12.
