### ISSUE TITLE
Means to resume interrupted pull process

### ISSUE THREAD

**Issue by anoduck** [radian-software/straight.el#1039]
It has occurred three or four times now, I am in the middle of performing a `straight-pull-all`  request and for whatever reason the process is interrupted. Either a repository conflict occurred, or Emacs froze, whatever... The process of pulling and process all of those repositories is fairly load intensive, for my old box at least, and it does occupy my session of Emacs that could otherwise be in use. It is reasonable to understand, starting this process all over from the beginning is undesirable. So, what I am inquiring is if there is a method to resume the process once interrupted, or in the least, determining/knowing what repositories have completed processing and which have not?

**Comment by raxod502** [comment]
That's quite reasonable. The first and simplest suggestion I would have is to try out `M-x straight-x-fetch-all` (you have to load `straight-x` first). It's a lot faster.

When I don't want to do that, typically I will `M-x straight-fetch-all` first followed by `M-x straight-merge-all` separately. It is the same effect, but the step that takes the longest (fetch) is separated from the step that requires interactivity (merge).

**Comment by anoduck** [comment]
Ah, snap! That is super cool. I will give it a try. Thanks!

**Comment by anoduck** [comment]
A-Mazing!!! That worked so good. Definitely doing that from now on.
