### ISSUE TITLE
Error when using ob-fsharp

### ISSUE THREAD

**Issue by 64J0** [radian-software/straight.el#1048]
## Description:

Hello people, hope you're good. I'm currently facing a problem with the package `ob-fsharp`. The configuration I'm using is this:

```elisp
;; Code evaluation in org-mode
(use-package ob-fsharp
  :straight (ob-fsharp
             :type git
             :host github
             :repo "juergenhoetzel/ob-fsharp"
             :branch master))
```

Then, during the initialization, I get this error:

> Error (use-package): org/:config: Cannot open load file: No such file or directory, ob-fsharp

My org configuration, for the concerning part:

```elisp
(use-package org
  :straight t
  ;; ...
  :config
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((sql      . t)
     (latex    . t)
     (shell    . t)
     (python   . t)
     (js       . t)
     (plantuml . t)
     (ditaa    . t)
     (C        . t)
     (org      . t)
     (fsharp   . t))))
```

Am I missing something?

---

Straight.el version: `prerelease (HEAD -> master, origin/master, origin/HEAD) 3eca39d 2022-11-25`

**Comment by 64J0** [comment]
I'm not sure if it could be related, but the `ob-fsharp` configuration appears after the `org` package configuration in my .emacs file.

**Comment by 64J0** [comment]
https://github.com/64J0/Emacs-config/blob/master/src/org-mode.el

**Comment by 64J0** [comment]
Also, I noticed that we don't have a receipt for the `ob-fsharp` package. How can I add it?

**Comment by progfolio** [comment]
Everything appears to install correctly with the following test case.


<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :user-dir "straight.ob-fsharp"
  :preserve t
  :post-bootstrap 
  (straight-use-package 'use-package)
  (use-package ob-fsharp :straight
    (ob-fsharp :host github :repo "juergenhoetzel/ob-fsharp")))
```
</details>

- Test run at: `2023-02-04 11:49:26`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> refactor/straight-get-recipe, fork/refactor/straight-get-recipe) 3525d4c 2023-01-29`
- emacs-version: `GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6)
 of 2023-01-23`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 3fa415c 2023-01-20
Cloning use-package...
Cloning use-package...done
Building use-package...
Building use-package → Building bind-key...
Building use-package → Building bind-key...done
Building use-package...
Building use-package...done
Cloning ob-fsharp...
Cloning ob-fsharp...done
Building ob-fsharp...
Building ob-fsharp → Cloning emacs-fsharp-mode...
Building ob-fsharp → Cloning emacs-fsharp-mode...done
Building ob-fsharp → Building fsharp-mode...
Building ob-fsharp → Building fsharp-mode...done
Building ob-fsharp...
Building ob-fsharp...done

Packages:
"straight"                n/a                  develop 3fa415c 2023-01-20
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master cd55f4fb 2023-01-30
"gnu-elpa-mirror"         n/a                  master 3350028 2023-02-03
"nongnu-elpa"             n/a                  main 85c7a060c6 2023-01-26
"el-get"                  melpa                master 17db7640 2023-01-28
"emacsmirror-mirror"      n/a                  master 03db6f7 2023-02-03
"use-package"             melpa                master 77945e0 2023-02-03
"bind-key"                melpa                master 77945e0 2023-02-03
"ob-fsharp"               melpa                master a5e893a 2022-11-13
"fsharp-mode"             melpa                master cfd3f88 2022-11-06


```
</details>

> Error (use-package): org/:config: Cannot open load file: No such file or directory, ob-fsharp

Note the issue is in org/:config: (not ob-fsharp).
`org-babel-do-load-languages` requires features associated with the languages in `org-babel-load-languages`:

```emacs-lisp
;;;###autoload
(defun org-babel-do-load-languages (sym value)
  "Load the languages defined in `org-babel-load-languages'."
  (set-default-toplevel-value sym value)
  (dolist (pair org-babel-load-languages)
    (let ((active (cdr pair)) (lang (symbol-name (car pair))))
      (if active
	  (require (intern (concat "ob-" lang)))
	(fmakunbound
	 (intern (concat "org-babel-execute:" lang)))
	(fmakunbound
	 (intern (concat "org-babel-expand-body:" lang)))))))
```

You'll need to add ob-fsharp to that list and `org-babel-do-load-languages` /after/ it has been installed/activated. You should be able to do so in the `:config` section of your use-package declaration for ob-fsharp. e.g.

```emacs-lisp
(add-to-list 'org-babel-load-languages (cons fsharp . t))
```

Does that help?

**Comment by 64J0** [comment]
@progfolio Thank you very much for this detailed answer, it definitely clarifies many parts of the error I'm facing. I'll test the approach you mentioned in my local setup! 🙌🏼 🚀

**Comment by 64J0** [comment]
> You'll need to add ob-fsharp to that list and org-babel-do-load-languages after it has been installed/activated. You should be able to do so in the :config section of your use-package declaration for ob-fsharp. e.g.
> 
> ```elisp
> (add-to-list 'org-babel-load-languages '(fsharp . t))
> ```

Confirming that this configuration worked in my local setup!

**Comment by 64J0** [comment]
Thanks for the help @progfolio, I'm going to close this issue now. Also, related to the recipe, thanks for the clarification!
