### ISSUE TITLE
Using straight to install corfu does not load extensions

### ISSUE THREAD

**Issue by aadi58002** [radian-software/straight.el#1051]
# Issue
I have installed corfu with straight.el and the extensions in corfu mode does not get loaded.

https://github.com/minad/corfu/issues/299

**Comment by progfolio** [comment]
duplicate of #968.
Please search to see if your issue has been reported before opening a new one.

**Comment by aadi58002** [comment]
> duplicate of #968. Please search to see if your issue has been reported before opening a new one.

Thanks for the reply i will keep in mind to search more thoroughly before opening a issue
