### ISSUE TITLE
Obsolete function "native-comp-deferred-compilation-deny-list"

### ISSUE THREAD

**Issue by stefanhusmann** [radian-software/straight.el#1053]
## What's wrong

When starting emacs 30.0.50 with --debug-init I get 
Symbol's value as variable is void: native-comp-deferred-compilation-deny-list

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
 ■  Warning (comp): straight.el:5236:33: Warning: ‘native-comp-deferred-compilation-deny-list’ is an obsolete variable (as of 29.1); use ‘native-comp-jit-compilation-deny-list’ instead.
 ■  Warning (comp): straight.el:5234:19: Warning: ‘native-comp-deferred-compilation-deny-list’ is an obsolete variable (as of 29.1); use ‘native-comp-jit-compilation-deny-list’ instead.

If I change the two lines in straight.el as suggested, the error vanishes.

I think this is due to commit
0be5f7ab6368175953c0a5bcbbd485fd9edda2b0

[0be5f7ab6368175953c0a5bcbbd485fd9edda2b0](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=0be5f7ab6368175953c0a5bcbbd485fd9edda2b0)

* Emacs version: 30.0.50 from git master
* Operating system: Arch Linux

**Comment by ps-143** [comment]
I observed this too. Today, I had to reinstall emacs and this error showed up while building straight.

- Emacs version: 30.0.50 from git master and also on emacs 29 from source.
- Operating system: Ubuntu 20.04

**Comment by raxod502** [comment]
Does https://github.com/radian-software/straight.el/pull/1054 fix it for you?

**Comment by dsedivec** [comment]
FYI just did a build of Emacs `master` tonight, hit this error, and #1054 did fix this for me.  Thanks as always!

**Comment by com4** [comment]
(specific commit for posterity: [95692f6754c3a8f55a90df2d6f7ce62be55cdcfc](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=95692f6754c3a8f55a90df2d6f7ce62be55cdcfc))

Fix #1054 works for me on 29.0.60

**Comment by andreyorst** [comment]
https://github.com/radian-software/straight.el/pull/1054 works for me on 29 and 30.0.50

**Comment by petergardfjall** [comment]
As I commented on [here](https://github.com/radian-software/straight.el/pull/1054#issuecomment-1437171407) https://github.com/radian-software/straight.el/pull/1054 resolves this issue for me.

(The `install.el` script appears broken for later `emacs-29` commits but that is perhaps a separate issue.)
