### ISSUE TITLE
Parallel package install during first install of emacs packages

### ISSUE THREAD

**Issue by aadi58002** [radian-software/straight.el#1055]
Hello there,
I recently switched from doom emacs to GNU emacs and started exclusively using straight.el to manage package.
I might be wrong on some of the below point please feel free to correct me if i am wrong.

When there are no package locally installed and you have to install them on the first start of emacs. It takes near 20 minutes (~102 packages) to completely install.

From what i have seen there are two steps to install a package :-
1. Clone the *.el files locally
2. Native compile them

#Question
Is it possible to pull the packages from github in parallel does for the first time package install as well?

I looked the straight-x-fetch-all which does seem to support parallel download of packages.

**Comment by aadi58002** [comment]
17m 39 seconds to install the following list of packages `https://pastebin.com/Q0HGwgqz`

**Comment by raxod502** [comment]
This is not currently supported. It would be quite desirable in my opinion but requires breaking changes to the interface that is provided by `straight.el`, which is currently fully synchronous (and changing that would break client code).

**Comment by kotatsuyaki** [comment]
I've come across this issue. My use case of frequent fresh package installs is that I build tarballs containing my configs and packages from time to time, and copy the tarballs into a (offline) corporate development environment. The build time is currently about 15 minutes for 50 packages.

**Comment by aadi58002** [comment]
You should try elpaca. After this issue I found out of elpaca it made my installs from over 20-25 min to around 2 min.

**Comment by kotatsuyaki** [comment]
I ended up still using straight.el, because elpaca does not support lock files.  See https://github.com/progfolio/elpaca/issues/151
