### ISSUE TITLE
Emacs daemon created by systemd dosen't work

### ISSUE THREAD

**Issue by SimoriccITA** [radian-software/straight.el#1057]
## What's wrong

If i try to create the daemon with ```systemctl --user start emacs``` (or enable it with  ```systemctl --user enable emacs```  and restart the session), the process is created but systemctl remain blocked for a while and gives a timeout error. The emacsclient doesn't find the daemon.
This happends only with [straight.el bootstrap code](https://github.com/radian-software/straight.el#getting-started)

## Directions to reproduce

1. use any .emacs.d folder that has the  [straight.el bootstrap code](https://github.com/radian-software/straight.el#getting-started) in the init.el file
2. try to start the emacs daemon with ```systemctl --user start emacs```

### Version information

* Emacs version: 28.2 (i tried even with emacs 27 an there is the same problem)
* Operating system: Arch linux

**Comment by raxod502** [comment]
I get this:

```
% journalctl --user -efu emacs
Feb 25 10:32:04 wit systemd[5009]: Starting Emacs text editor...
Feb 25 10:32:04 wit emacs[645356]: Warning: due to a long standing Gtk+ bug
Feb 25 10:32:04 wit emacs[645356]: https://gitlab.gnome.org/GNOME/gtk/issues/221
Feb 25 10:32:04 wit emacs[645356]: Emacs might crash when run in daemon mode and the X11 connection is unexpectedly lost.
Feb 25 10:32:04 wit emacs[645356]: Using an Emacs configured with --with-x-toolkit=lucid does not have this problem.
Feb 25 10:32:04 wit emacs[645356]: Rebuilding all packages due to change in Emacs version
Feb 25 10:32:04 wit emacs[645356]: Building straight...
Feb 25 10:32:04 wit systemd[5009]: emacs.service: Got notification message from PID 645358, but reception only permitted for main PID 645356
Feb 25 10:32:04 wit emacs[645356]: Building straight...done
Feb 25 10:32:04 wit emacs[645356]: Building use-package...
Feb 25 10:32:04 wit emacs[645356]: Building use-package → Building bind-key...
Feb 25 10:32:04 wit systemd[5009]: emacs.service: Got notification message from PID 645375, but reception only permitted for main PID 645356
Feb 25 10:32:04 wit emacs[645356]: Building use-package → Building bind-key...done
Feb 25 10:32:04 wit emacs[645356]: Building use-package...
```

Emacsclient is able to start and connect to the server successfully.

This is Emacs 28.1 on Pop!_OS 22.04.

**Comment by SimoriccITA** [comment]
I retried to test my config file and understood that straight.el has nothing to do with the problem, sorry for the mistaken bug report

**Comment by progfolio** [comment]
Not  a problem. Thank you for letting us know.
