### ISSUE TITLE
Conditional recipe

### ISSUE THREAD

**Issue by baracunatana** [radian-software/straight.el#1069]
Hi

I user `straight` and `use-package` to mantain an Emac's configuration that I use in two different systems; one is a NixOS and the other one is Ubuntu. Because of the peculiarities of NixOS, my recipe for `mu4e` is:

```
(use-package mu4e
   :straight (:local-repo 
       "/run/current-system/sw/share/emacs/site-lisp/mu4e"
       :pre-build ())
   ...)
```

It works just fine in NixOS, but that doesn't work in the Ubuntu machine as it doesn't need the `:straight` bit.

How can I tell `straight` to override the recipe for `mu4e` only if a given condition (like `(if (executable-find "nixos-rebuild") ...)`) is `t`?

**Comment by progfolio** [comment]
recipes can be backquoted forms. e.g.

```emacs-lisp
(use-package mu4e
  :straight `(:local-repo ,(if (executable-find "nixos-rebuild") "etc" "else"))))
```
