### ISSUE TITLE
ox-reveal: org-reveal--using-hilight.js: Symbol's function definition is void: highlight

### ISSUE THREAD

**Issue by luftmensch-luftmensch** [radian-software/straight.el#1070]
## What's wrong
I'm trying to install [org-reveal](https://github.com/yjwen/org-reveal) using straight.
Unfortunately after doing it and followed the instruction (requiring `ox-reveal`) I'm able to use it due to a symbol void definition `org-reveal--using-highlight.js: Symbol’s function definition is void: highlight`).

This dont' happen when cloning the repository manually -> loading file -> requiring it

### Version information

* Emacs version: `GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.35, cairo version 1.16.0)`
* Operating system: NixOS 22.05

**Comment by progfolio** [comment]
Hi. Thanks for taking the time to fill out a bug report.
Unfortunately, I'm unable to reproduce the error with the following test case:


<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :post-bootstrap 
  (straight-use-package 'ox-reveal)
  (require 'ox-reveal))
```
</details>

- Test run at: `2023-03-30 16:39:16`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) 039e5c9 2023-03-12`
- emacs-version: `GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.17.8)
 of 2023-03-24`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 039e5c9 2023-03-12
Cloning org-reveal (for ox-reveal)...
Cloning org-reveal (for ox-reveal)...done
Building ox-reveal...
Building ox-reveal → Cloning org...
Building ox-reveal → Cloning org...done
Building ox-reveal → Building org...
Building ox-reveal → Building org...done
Building ox-reveal...
Building ox-reveal...done

Packages:
"straight"                n/a                  develop 039e5c9 2023-03-12
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 263469b4 2023-03-30
"gnu-elpa-mirror"         n/a                  master 3d084e3 2023-03-27
"nongnu-elpa"             n/a                  main 0120f3d 2023-03-14
"el-get"                  melpa                master 22c83206 2023-03-19
"emacsmirror-mirror"      n/a                  master cd4fa91 2023-03-27
"ox-reveal"               melpa                master f55c851 2022-11-27
"org"                     org-elpa             main 1a6d5f11d 2023-03-29


```
</details>

Please:

1. Evaluate the above test case in your \*scratch* buffer. It will install straight.el and the package in a clean environment. Once the tests finishes please share the contents of the \*straight-bug-report-process* buffer here.

2. If there are any other steps beyond `(require 'ox-reveal)` necessary to trigger the error, please add them to the `:post-bootstrap` section of the test case and share that here.

**Comment by luftmensch-luftmensch** [comment]
Thanks for the quick response!
I've tested as asked
<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :post-bootstrap 
  (straight-use-package 'ox-reveal)
  (require 'ox-reveal))
```
</details>

- Test run at: `2023-03-30 22:51:49`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) 039e5c9 2023-03-12`
- emacs-version: `GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.35, cairo version 1.16.0)`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 039e5c9 2023-03-12
Cloning org-reveal (for ox-reveal)...
Cloning org-reveal (for ox-reveal)...done
Building ox-reveal...
Building ox-reveal → Cloning org...
Building ox-reveal → Cloning org...done
Building ox-reveal → Building org...
Building ox-reveal → Building org...done
Building ox-reveal...
Building ox-reveal...done

Packages:
"straight"                n/a                  develop 039e5c9 2023-03-12
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 263469b4 2023-03-30
"gnu-elpa-mirror"         n/a                  master 3d084e3 2023-03-27
"nongnu-elpa"             n/a                  main 0120f3d 2023-03-14
"el-get"                  melpa                master 22c83206 2023-03-19
"emacsmirror-mirror"      n/a                  master cd4fa91 2023-03-27
"ox-reveal"               melpa                master f55c851 2022-11-27
"org"                     org-elpa             main 1a6d5f11d 2023-03-29


```
</details>

I've forgot to point that the error will show only when trying to call `org-export-dipatch` and trying to export as `reveal.js HTML Presentation`

**Comment by progfolio** [comment]
> I've forgot to point that the error will show only when trying to call org-export-dipatch and trying to export as reveal.js HTML Presentation.

I don't have reveal.js installed, but I was able to export without hitting the error you initially described.
You can try the test again interctively by adding `:interactive t`:

```emacs-lisp
(straight-bug-report
  :interactive t
  :post-bootstrap 
  (straight-use-package 'ox-reveal)
  (require 'ox-reveal))
```

I would try that and see if the same error is thrown.

**Comment by luftmensch-luftmensch** [comment]
Strangely enought I cannot replicate the error using this snippet. Don't know what it broken in my configuration then

**Comment by progfolio** [comment]
> 

I would start by bisecting the init file (removing half of it, testing, repeating) to pinpoint what's causing the error.
Closing this issue for now, but let us know if you narrow it down and it's due to straight.el. Thanks.

**Comment by luftmensch-luftmensch** [comment]
> > 
> 
> I would start by bisecting the init file (removing half of it, testing, repeating) to pinpoint what's causing the error. Closing this issue for now, but let us know if you narrow it down and it's due to straight.el. Thanks.

Hi again. I've started a clean installation only with the setup to install straight (and no other configuration for any package).

Unfortunately I've got the same errors encountered (void definition of highlight), so I'm assuming it a straight related thing (?).

There is some other action I can do to test it?

**Comment by progfolio** [comment]
Please include the exact steps (and files)  you are using to reproduce the issue.

**Comment by luftmensch-luftmensch** [comment]
Starting with a blank `init.el` file 
Include the steps to initialize `straight.el` as shown:
```
(setq straight-repository-branch "develop") ;; Only way to use straight on bleeding edge emacs as shown https://github.com/radian-software/straight.el/issues/1060

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
	 ;; Old link https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el was moved to radian-software
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
;;; straight.el configuration ends here

;;; leaf.el setup
(eval-and-compile
;; <leaf-install-code>
  (straight-use-package 'leaf)
  (straight-use-package 'leaf-keywords)
  (straight-use-package 'blackout)
  (straight-use-package 'diminish)
  
  (leaf leaf-keywords
    (straight-use-package 'leaf-keywords)
    :init
    (leaf blackout (straight-use-package 'blackout))
    (leaf diminish (straight-use-package 'diminish))
    (leaf el-get :custom ((el-get-git-shallow-clone . t)))
    :config
    (leaf-keywords-init)))
```

After doing that try to install `org-reveal` using `(straight-use-package 'org-reveal)`

Call `(require 'ox-reveal)` and then call `org-export-dispatch` and call one of the `Reveal.js` options

Aspected output -> exported `Reveal.js` html file
Current output -> `org-reveal--using-highlight.js: Symbol’s function definition is void: highlight`

**Comment by progfolio** [comment]
with any org file?

**Comment by luftmensch-luftmensch** [comment]
> with any org file?

Yes

**Comment by raxod502** [comment]
I followed the steps in https://github.com/radian-software/straight.el/issues/1070#issuecomment-1492271758 and was unable to reproduce the issue - html file was written successfully when selecting to export a reveal.js presentation from my org file.

I'd dig into the Org source code to see what's referencing that variable and where it's supposed to be defined.

**Comment by luftmensch-luftmensch** [comment]
Apparently it was a mix of latest build of emacs which I was running and org modern package that breaks it. Now it's working properly.
