### ISSUE TITLE
Problem installing new packages using straight.el

### ISSUE THREAD

**Issue by kebairia** [radian-software/straight.el#1074]
Greetings everyone
Lately I was trying to install some packages with `straight.el` as usual.

After using `M-x straight-use-package` I got the following message in the buffer. 

![2023-04-06-1680790992_835x55](https://user-images.githubusercontent.com/3621146/230621189-d68b88fc-5244-4b49-b0e8-3fa8a7686c7a.png)

It took a very long time, and then there was this error message.
![2023-04-07-1680875892_938x430](https://user-images.githubusercontent.com/3621146/230621219-914329cb-09e3-40ae-afcd-01c4aa2ceeb3.png)

Can anyone help me with this please ?!

**Comment by progfolio** [comment]
Please see #994
Should be fixed on the "develop" branch

**Comment by kebairia** [comment]
Alright, Thanks @progfolio
