### ISSUE TITLE
What is the current proper way to config AucTex in straight? 

### ISSUE THREAD

**Issue by rickalex21** [radian-software/straight.el#1079]
@raxod502 What is the current proper way to config AucTex in straight? Before I moved
to straight all I did was `ensure auctex`  and had `require tex` and everything worked fine. 
I took the suggestion in #240 and added `latex`, not sure if this the correct way or where
`Tex-command-master` command is found?

This is my current config:

```lisp
(straight-use-package '(auctex :source el-get
                        :files ("*.el" "*.info" "dir"
                                "doc" "etc" "images" "latex" "style")))
(require 'tex-site)
(require 'preview-latex)

(use-package latex
  ;; :ensure auctex ; makes latex easier to use
  :straight auctex
  :demand t
  :init
  (setq TeX-PDF-mode t) ; compile tex as PDF
  (setq TeX-command-force "LaTex") ; Don’t ask for options like View, Latex etc..
  (setq TeX-view-program-list '(("zathura" "zathura %o"))
            TeX-view-program-selection '((output-pdf "zathura")))
  (add-hook 'LaTeX-mode-hook 'TeX-source-correlate-mode)
  (setq TeX-source-correlate-start-server t)
  (add-hook 'LaTeX-mode-hook
        (lambda ()
          (add-hook 'after-save-hook 'TeX-command-master nil t)))
  :config
  ;;(my/map-keys `(("C-c l l" ,#'Tex-command-master "pdf")) 'org-mode-map)
)
```

_Originally posted by @rickalex21 in https://github.com/radian-software/straight.el/issues/240#issuecomment-1500990797_

**Comment by raxod502** [comment]
This works fine for me: https://github.com/radian-software/radian/blob/f403244e244ccca695ff6c73c62b1265e521afa7/emacs/radian.el#L3386-L3506

Are you encountering an issue with your configuration?

**Comment by rickalex21** [comment]
@raxod502 Sorry for the delay I did not see this notification. It seems to be working
fine now after a few loops that I had to through. I don't use Latex much so when I
do, I will come back and post here if I encounter any problems.

Speaking of loops..... I keep getting this message for my local packages.
They are my packages without git. When I edit my file I want it to native compile
automatically when I reload emacs.

```text
Source file ‘~/.config/emacs/.cache/straight/build-28.2/my-pgk/my-pkg.el’ newer than byte-compiled file; using older file
```

I read that `load-prefer-newer` fixes this but then it's not native comp.

Here is the config, I am wanting to use my packages with straight. Just for the
record I'm not sure if I'm doing this right.

```lisp
(cl-loop for pkg in (list
'my-pkg
'another-pkg
)
do
(straight-use-package
 (list pkg
       ;;:build '(autoloads compile native-compile info)
       :files (list (format "%s.el" pkg))
       :local-repo (format "/home/ritchie/.config/emacs/lisp/%s/" pkg) :type nil ))
(require pkg)
)
```

I did find three other similar issues, I am on the develop. This is my config.


```lisp
(setq
  ;;Set `use-package' when it's started in verbose mode
  use-package-verbose t
  ;;Defer loading packages by default, use `:demand' to force loading a package
  use-package-always-defer t
  ;; Don't uncomment will break things.
  ;;straight-use-package-by-default t
  straight-base-dir (expand-file-name  ".cache/" user-emacs-directory)
  ;; Add Emacs version and the Git hash to the build directory to avoid problems
  straight-build-dir (format "build-%s%s" emacs-version
                              (if emacs-repository-version
                                (format "-%s" (substring emacs-repository-version 0 8)) ""))
 straight-repository-branch "develop"
 ;; Do not clone all project history, just the last worktree (--depth 1)
 straight-vc-git-default-clone-depth '(1 single-branch)
 ;; Do not slow startup by checking for package modifs, check only on demand
 straight-check-for-modifications '(check-on-save find-when-checking))

;; Bootstraping straight.el
(defvar bootstrap-version)
(let ((bootstrap-file (concat straight-base-dir "straight/repos/straight.el/bootstrap.el"))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)

```

I could use my own code `my/load` but why not use straight right since I have
things that are looking like packages now right?

```lisp
(defun my/load (feature)
  "Native Compile or require. Make sure use-package is not in the module."
  (if (native-comp-available-p)
      (progn (let* ((file (locate-library (format "%s" feature)))
                    (feln (concat (car native-comp-eln-load-path)"mine/"(file-name-sans-extension (file-name-nondirectory file))".eln")))
               (cond ( (not (file-exists-p feln)) (progn (load (native-compile file feln) nil t) )) ; eln does not exist
                     ( (file-newer-than-file-p file feln) (progn (load (native-compile file feln) nil t)))) ; file is newer than eln
               (load feln nil t)))
    (require feature)))

```

**Comment by raxod502** [comment]
`straight.el` byte-compiles and native-compiles packages by default when they are built. If you are seeing that warning then something has gone wrong with that system. The first thing to check is if you can manually trigger rebuilds with `M-x straight-rebuild-package`. Then check the modification detection system settings in your configuration.

**Comment by rickalex21** [comment]
It does work with `M-x straight-rebuild-package` once I restart but when a file is
modified should it not automatically build and load the package on start up
automatically?

>Then check the modification detection system settings in your configuration.

I have not done much with my configuration all the straight configuration is above.
I do not tweak straight outside of what it is show above.

There is another problem I had yesterday and I am not sure if it is a straight issue
but for some reason I get `void-function org-clock-kill-emacs-query` when trying
to quit emacs. I do not mess with the org code at all. As a work around:

```lisp
(autoload 'org-clock-kill-emacs-query "org-clock")
```

I am not sure if straight was suppose to load this or this is an optional package. I did
not add this function to a hook. I am not sure why org or any one would hook this
function when org-clock.el is required.

**Comment by rickalex21** [comment]
I'm not sure I understand. Is it suppose to create a file in the straight/modified
directory? It's not creating a file.

To make the expression execute I did this:

```lisp
(straight-register-repo-modification "one-mine")
```
I also tried this:

```lisp
(straight-register-repo-modification "~/.config/emacs/lisp/one-mine/")
```
My code:

```lisp
(cl-loop for pkg in (list
'one-mine
'two-mine
)
do
(straight-use-package
 (list pkg
       ;;:build '(autoloads compile native-compile info)
       :files (list (format "%s.el" pkg))
       :local-repo (format "/home/ritchie/.config/emacs/lisp/%s/" pkg) :type nil ))
(require pkg)
)
```

I am still getting the message:

```text
Source file ‘/home/ritchie/.config/emacs/.cache/straight/build-28.2/one-mine/one-mine.el’ newer than byte-compiled file; using older file
```
I get the same message when modify other packages that are not mine under
git source control in straight/repos. I understand what I want will slow
down my startup time but that's ok because I don't modify things all the time,
only when I need to check on something or see how it works.

**Comment by raxod502** [comment]
Oh, you're saying that even when evaluating `(straight-register-repo-modification "one-mine")` manually, there is no file created called `~/.emacs.d/straight/modified/one-mine`? The file gets created for me. You should look into why that function is not creating a file, it seems pretty straightforward that it should just looking at its implementation.

**Comment by raxod502** [comment]
It's hard for me to help because I don't have good insight into your environment. That's not your fault however, we should have tools for this. I have started https://github.com/radian-software/straight.el/pull/1110 to solve this problem and will get back to you with further diagnostic suggestions.

**Comment by rickalex21** [comment]
Thanks for all your help. If I figure something out I'll come back and post. I don't know what else
to mention. I think when I update with `straight-pull-all` it should automatically do this and not
warn about source files newer than build but not saying it's your fault, it's unknown what the
problem is for now...

**Comment by raxod502** [comment]
Ok, I added https://github.com/radian-software/straight.el/pull/1110 and https://github.com/radian-software/straight.el/pull/1115 so that you could run again and I would have enough logs to find the problem. But while adding the logs I found the problem myself: https://github.com/radian-software/straight.el/pull/1116

**Comment by raxod502** [comment]
> it says compilation has finished

What does, exactly? Is this a message from `straight.el`? If so, what's the exact wording?
