### ISSUE TITLE
ob-php broken : repo URL does not respond

### ISSUE THREAD

**Issue by liar666** [radian-software/straight.el#1082]
## What's wrong

In DoomEmacs, running `doom upgrade` breaks (see https://github.com/doomemacs/doomemacs/issues/7214 )

## Directions to reproduce

Error comes from the fact that `ob-php` repo URL does not exist anymore: Going into `~/.emacs.d/.local/straight/repos/ob-php/` and running `git fetch` runs forever... Then outputs:
```
fatal: unable to access 'https://repo.or.cz/ob-php.git/': Failed to connect to repo.or.cz port 443 after 129747
```

### Version information

* Emacs version: 28.1 / Doom  3.0.0-pre
* Operating system: Ubuntu 22.04.2 LTS

**Comment by progfolio** [comment]
Unable to reproduce sans Doom:


<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :post-bootstrap 
  (straight-use-package 'ob-php))
```
</details>

- Test run at: `2023-05-02 14:49:36`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> master, origin/master, origin/develop, origin/HEAD, develop) 039e5c9 2023-03-12`
- emacs-version: `GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.17.8)
 of 2023-04-14`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/master, origin/develop, origin/HEAD) 039e5c9 2023-03-12
Cloning ob-php...
Cloning ob-php...done
Building ob-php...
Building ob-php → Cloning org...
Building ob-php → Cloning org...done
Building ob-php → Building org...
Building ob-php → Building org...done
Building ob-php...
Building ob-php...done

Packages:
"straight"                n/a                  develop 039e5c9 2023-03-12
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 86ca8d06 2023-05-02
"gnu-elpa-mirror"         n/a                  master eda4c96 2023-05-01
"nongnu-elpa"             n/a                  main 0120f3d 2023-03-14
"el-get"                  melpa                master 22c83206 2023-03-19
"emacsmirror-mirror"      n/a                  master 606c3dc 2023-05-02
"ob-php"                  melpa                master 6ebf779 2022-02-21
"org"                     org-elpa             main 5ec364a1a 2023-05-02


```
</details>

Are you able to reproduce the issue sans Doom or by directly trying to clone the repository from the command line?:

```bash
git clone https://repo.or.cz/ob-php.git/
```

**Comment by liar666** [comment]
Hi,

Thanks for the quick response.

Indeed, `git clone` is working today. And `doom upgrade seems to have succeeded too.`

Was apparently a network problem in the end, but I don't think it was a problem on my end, as I tested the URL with:
https://downforeveryoneorjustme.com/
which told me that it was "down for everyone".

Thanks anyway!
