### ISSUE TITLE
JCS-ELPA supports in straight.el.

### ISSUE THREAD

**Issue by hongyi-zhao** [radian-software/straight.el#1084]
I'm not sure whether `straight.el` has added the [JCS-ELPA](https://jcs-emacs.github.io/jcs-elpa/) repository to its package archives list to use the corresponding recipes. Any tips will be appreciated. I noticed the [JCS-ELPA](https://jcs-emacs.github.io/jcs-elpa/) repository [here](https://jcs-emacs.github.io/jcs-elpa/).

Regards,
Zhao

**Comment by hongyi-zhao** [comment]
Based on tries, it seems that it must installed as follows:

```elisp
(use-package openai
  :straight (openai :type git :host github :repo "emacs-openai/openai"))
(use-package chatgpt
  :straight (chatgpt :type git :host github :repo "emacs-openai/chatgpt"))
```

**Comment by progfolio** [comment]
https://github.com/radian-software/straight.el#getting-started

> You should remove any code that relates to package.el; for example, references to package-initialize, package-archives, and (if you're using [use-package](https://github.com/jwiegley/use-package)) :ensure or use-package-always-ensure.

`:ensure` is for using package.el with use-package. You'd want to use the `:straight` keyword in its place.

**Comment by hongyi-zhao** [comment]
So, I must use straight as follows when working via [Integration with use-package](https://github.com/radian-software/straight.el#integration-with-use-package):

> Based on my tries, it seems that it must be installed as follows:
> 
> ```emacs-lisp
> (use-package openai
>   :straight (openai :type git :host github :repo "emacs-openai/openai"))
> (use-package chatgpt
>   :straight (chatgpt :type git :host github :repo "emacs-openai/chatgpt"))
> ```

**Comment by raxod502** [comment]
Sorry, what exactly is JCS-ELPA? I'm not entirely clear from reading the docs at https://github.com/jcs-emacs/jcs-elpa. What differentiates this repository from MELPA? Why does it exist separately?

**Comment by hongyi-zhao** [comment]
It's for https://github.com/jcs-emacs/jcs-emacs, IMO.

**Comment by raxod502** [comment]
I get that, but it sounded like you were saying it should be added to `straight.el`?

**Comment by hongyi-zhao** [comment]
I say so because I noticed that this repository includes some packages which doesn't cover by MELPA, say, the following:

https://github.com/emacs-openai/chatgpt

**Comment by raxod502** [comment]
Is there a reason not to submit those to MELPA instead?

**Comment by hongyi-zhao** [comment]
No idea.

**Comment by raxod502** [comment]
I'd err on the side of doing that, then, rather than trying to add this repo to `straight.el`.
