### ISSUE TITLE
Initial installation should support redirect

### ISSUE THREAD

**Issue by doingitforfree** [radian-software/straight.el#1086]
Cleared my straight/ directory and reloaded my configuration, which halted with a connection error. On investigating, raw.githubusercontent.com is banned by my ISP (largest in India).

Therefore, there should be a redirect when the URL is not available.

## Directions to reproduce

- `rm -rf ~/.config/emacs/straight`
- Connect to a network hosted by a shitty ISP
- `emacs`

https://github.com/orgs/community/discussions/32889
https://teddit.net/r/india/comments/zd7ykr/jio_has_blocked_rawgithubusercontentcom_again/

**Comment by doingitforfree** [comment]
> Are other GitHub domains also affected?
Viewing/Cloning github repositories work fine. That is probably why I never noticed this issue until I reinstalled straight.el

> Do you have a working proxy?
Not anything that I know of.

**Comment by raxod502** [comment]
I enabled GitHub Pages for this repository. If you replace `https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el` with `https://radian-software.github.io/straight.el/install.el` does it work?

**Comment by doingitforfree** [comment]
That fixes it.

```
➜ wget 'https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el'
--2023-05-28 07:58:28--  https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... [...], [...]
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|[...]|:443... failed: Connection timed out.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|[...]|:443... failed: Connection timed out.
```

```
➜ wget 'https://radian-software.github.io/straight.el/install.el'
--2023-05-28 07:58:45--  https://radian-software.github.io/straight.el/install.el
Resolving radian-software.github.io (radian-software.github.io)... [...], [...], ...
Connecting to radian-software.github.io (radian-software.github.io)|[...]|:443... connected.

HTTP request sent, awaiting response... 200 OK
Length: 13189 (13K) [application/octet-stream]
Saving to: ‘install.el’

install.el                                 100%[=====================================================================================>]  12.88K  --.-KB/s    in 0s

2023-05-28 07:58:46 (30.4 MB/s) - ‘install.el’ saved [13189/13189]
```
