### ISSUE TITLE
embark-org.el file missing

### ISSUE THREAD

**Issue by WorldsEndless** [radian-software/straight.el#1087]
This is a repeat of https://github.com/radian-software/straight.el/issues/1046 because I cannot re-open that issue. I have tried the fixes mentioned there and more, but to no avail.

## What's wrong
when straight builds the embark package, it omits the embark-org.el file which is present in its embark repository directory. This results in blocking errors as I have things that depend upon functions from embark-org.  

## Directions to reproduce
```
(use-package embark)
```
The repository includes a embark-org.el at the top level, but the straight build does not. Errors follow that the embark-org file cannot be found. 

Bug report and information should be as in the linked issue. 

### Version information
* Emacs version: GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)
* Operating system: Linux (Gnu GUIX)

**Comment by progfolio** [comment]
If I had to guess, the MELPA recipe was originally overly specific (only including certain files), and then changed to add the file that is missing now. Have you tried `M-x straight-pull-recipe-repositories` to see if the recipe has changed?

The file is present in the following test case:


<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :post-bootstrap 
  (straight-use-package 'embark)
  (let
      ((default-directory
        (straight--build-dir "embark")))
    (message "%S"
             (straight--process-output "ls" "-lah"))))
```
</details>

- Test run at: `2023-05-17 11:05:30`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> master, origin/master, origin/develop, origin/HEAD, develop) 039e5c9 2023-03-12`
- emacs-version: `GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.17.8)
 of 2023-05-07`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/master, origin/develop, origin/HEAD) 039e5c9 2023-03-12
Cloning embark...
Cloning embark...done
Building embark...
Building embark → Cloning compat...
Building embark → Cloning compat...done
Building embark → Building compat...
Building embark → Building compat...done
Building embark...
Building embark...done

"total 256K
drwxr-xr-x 2 n n  200 May 17 11:05 .
drwxr-xr-x 5 n n  100 May 17 11:05 ..
-rw-r--r-- 1 n n  639 May 17 11:05 dir
-rw-r--r-- 1 n n 8.1K May 17 11:05 embark-autoloads.el
lrwxrwxrwx 1 n n   60 May 17 11:05 embark.el -> /tmp/straight.el-test-kqU4Uc/straight/repos/embark/embark.el
-rw-r--r-- 1 n n 155K May 17 11:05 embark.elc
-rw-r--r-- 1 n n  68K May 17 11:05 embark.info
lrwxrwxrwx 1 n n   64 May 17 11:05 embark-org.el -> /tmp/straight.el-test-kqU4Uc/straight/repos/embark/embark-org.el
-rw-r--r-- 1 n n  14K May 17 11:05 embark-org.elc
lrwxrwxrwx 1 n n   62 May 17 11:05 embark.texi -> /tmp/straight.el-test-kqU4Uc/straight/repos/embark/embark.texi"
Packages:
"straight"                n/a                  develop 039e5c9 2023-03-12
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 127b93c5 2023-05-14
"gnu-elpa-mirror"         n/a                  master ca8f25a 2023-05-14
"nongnu-elpa"             n/a                  main 83410aa 2023-05-15
"el-get"                  melpa                master 46be7740 2023-05-14
"emacsmirror-mirror"      n/a                  master 1d9d0af 2023-05-16
"embark"                  melpa                master ab920ea 2023-05-11
"compat"                  gnu-elpa-mirror      master 81ae800 2023-05-11


```
</details>

**Comment by WorldsEndless** [comment]
Using that test case I get the same encouraging result. But for whatever reason, the -org file does NOT actually appear in the build directory. I've updated the recipes but no difference. 

<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :post-bootstrap 
  (straight-use-package 'embark)
  (let
      ((default-directory
	 (straight--build-dir "embark")))
    (message "%S"
	     (straight--process-output "ls" "-lah"))))
```
</details>

- Test run at: `2023-05-17 12:07:05`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> master, origin/master, origin/develop, origin/HEAD, develop) 039e5c9 2023-03-12`
- emacs-version: `GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/master, origin/develop, origin/HEAD) 039e5c9 2023-03-12
Cloning embark...
Cloning embark...done
Building embark...
Building embark → Cloning compat...
Building embark → Cloning compat...done
Building embark → Building compat...
Building embark → Building compat...done
Building embark...
Building embark...done

"total 204K
drwxr-xr-x 2 torysa users 4.0K May 17 12:07 .
drwxr-xr-x 5 torysa users 4.0K May 17 12:07 ..
-rw-r--r-- 1 torysa users 8.2K May 17 12:07 embark-autoloads.el
lrwxrwxrwx 1 torysa users   99 May 17 12:06 embark.el -> /home/torysa/emacs/.emacs.d/temporary_files/straight.el-test-AgBxiF/straight/repos/embark/embark.el
-rw-r--r-- 1 torysa users 155K May 17 12:07 embark.elc
lrwxrwxrwx 1 torysa users  103 May 17 12:06 embark-org.el -> /home/torysa/emacs/.emacs.d/temporary_files/straight.el-test-AgBxiF/straight/repos/embark/embark-org.el
-rw-r--r-- 1 torysa users  14K May 17 12:07 embark-org.elc
lrwxrwxrwx 1 torysa users  101 May 17 12:06 embark.texi -> /home/torysa/emacs/.emacs.d/temporary_files/straight.el-test-AgBxiF/straight/repos/embark/embark.texi"
Packages:
"straight"                n/a                  develop 039e5c9 2023-03-12
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 127b93c5 2023-05-14
"gnu-elpa-mirror"         n/a                  master ca8f25a 2023-05-14
"nongnu-elpa"             n/a                  main 83410aa 2023-05-15
"el-get"                  melpa                master 46be7740 2023-05-14
"emacsmirror-mirror"      n/a                  master 1d9d0af 2023-05-16
"embark"                  melpa                master ab920ea 2023-05-11
"compat"                  gnu-elpa-mirror      master 81ae800 2023-05-11


```
</details>

**Comment by progfolio** [comment]
> But for whatever reason, the -org file does NOT actually appear in the build directory.

Just so we're on the same page. You mean the file in the /tmp/$TESTDIR/build/embark directory, but does not show up in your config's $BUILD/embark/ directory, correct? That's how I'm interpreting the output of that test.

>  I've updated the recipes but no difference.

Please share the output of `M-x straight-get-recipe` `embark`.
I would also try deleting `$STRAIGHT/repos/embark` and `$STRAIGHT/builds/embark` and re-installing now that you've pulled the recipe repositories.

**Comment by WorldsEndless** [comment]
Nicholas Vollmer ***@***.***> writes:

> Just so we're on the same page. You mean the file in the /tmp/$TESTDIR/build/embark directory, but does not show up in your config's
> $BUILD/embark/ directory, correct? That's how I'm interpreting the output of that test.
That is correct. The repo and even the testdir have the embark-org.el file, but the actual $BUILD/embark directory does NOT receive one of those. 

>  I've updated the recipes but no difference.
>
> Please share the output of M-x straight-get-recipe embark.
To my surprise, when I try =M-x straight-get-recipe embark= I see the completion option, which include embark-consult, embark-vc, citar-embark, mpdel-embark, and avy-embark-collect, but NOTHING for plain-old-Embark.

> I would also try deleting $STRAIGHT/repos/embark and $STRAIGHT/builds/embark and re-installing now that you've pulled the recipe
> repositories.

Ok. Per your recommendation I just tried it and the resulting embark directories are the same, where repos/ has the file but the build does not. Exploring a little more, I noticed that my straight/build-cache-el ALSO, noticeably, lacks the embark-org file:

```lisp
(:type git :host github :repo "oantolin/embark" :files ("embark.el" "embark.texi" "embark-pkg.el") :flavor melpa :package "embark" :local-repo "embark")
```

I'm not entirely sure how that file works so I tried manually adding embark-org.el to the list but it was wiped out the next time I tried to build.

**Comment by progfolio** [comment]
Sounds like the build cache is stale.
Closing Emacs.
I would try deleting repos/embark and build/embark again.
Editing the build-cache.el file via `emacs -q` or another editor and removing the entry for embark.
Start Emacs.

**Comment by WorldsEndless** [comment]
Jackpot! I'm using exwm and a literate config, so I tried to get away without restarting my main process. What brought the solution (ie a BUILD/embark/embark-org.el):

1. Delete BUILD/embark
2. Delete REPOS/embark
3. Delete every sexp that mentioned "embark" from straight/build-cache.el
4. Restart an emacs process, which Straight to run and get build new embark things... and this time they included embark-org.el

I wonder what caused this problem in the first place?

**Comment by oantolin** [comment]
> If I had to guess, the MELPA recipe was originally overly specific  (only including certain files instead of relying on the default values), and then changed to add the file that is missing now.

I agree with everything except the word "overly". 😉
