### ISSUE TITLE
Some problems when using `straight-pull-all` to update all installed packages to their latest commit versions.

### ISSUE THREAD

**Issue by hongyi-zhao** [radian-software/straight.el#1088]
I try to use `straight-pull-all` to update all installed packages to their latest commit versions, but I noticed some problems as described below:

1. For a package whose remote repository has been changed, say the following one:

![image](https://github.com/radian-software/straight.el/assets/11155854/4d79e0df-2a41-4ff8-bbd7-bd44996101b1)

After I selected the `d` option, it seems that the repository hasn't been updated. So I try to update it manually by running `git pull`, but the following information will be triggered:

```shell
werner@X10DAi:~/.emacs.d/straight/repos/tablist$ git pull 
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master
```
So, in order to do the update correctly, I must issue the following command:

```shell
werner@X10DAi:~/.emacs.d/straight/repos/tablist$ git branch --set-upstream-to=origin/master  master
branch 'master' set up to track 'origin/master'.
werner@X10DAi:~/.emacs.d/straight/repos/tablist$ git pull 
Already up to date.
```

But I think all the above steps should be done by `straight-pull-all` automatically in this case.

2. In addition, I encountered the following problem, but do not know how to solve:

![image](https://github.com/radian-software/straight.el/assets/11155854/0b02b9ff-d4c8-47e0-9804-36f189839f81)

Regards,
Zhao

**Comment by raxod502** [comment]
We need more information. For 1, what was the Git state before and after `straight-pull-all`? For 2, what is the error message in `*straight-process*`?

**Comment by hongyi-zhao** [comment]
In addition to the above problems, I also encountered the following problems:

![image](https://github.com/radian-software/straight.el/assets/11155854/39e1d1bc-7f15-47e8-82f6-f19b178d2d2e)

Then pressing `m` will trigger the following:

![image](https://github.com/radian-software/straight.el/assets/11155854/d08e933f-2440-4727-9d52-0fa7ba8e2744)

**Comment by raxod502** [comment]
That seems expected. You asked for a merge, there was a conflict, so it needs to be resolved by the user.

**Comment by hongyi-zhao** [comment]
In any case, if I am not the developer of the corresponding package, but have these problems due to occasional changes to the contents of the repository or other unforeseen reasons, then the most effective way to solve such problems is to delete them and let `straight` clone them from scratch.

**Comment by raxod502** [comment]
That is one approach. I still don't think we've got enough information to help solve these problems automatically though, so closing the issue for now since it seems you've found a preferred workaround.
