### ISSUE TITLE
How do you evaluate .el files from a github repo?

### ISSUE THREAD

**Issue by danielkrajnik** [radian-software/straight.el#1090]
I am struggling to install [htmlz-mode](https://github.com/0xekez/htmlz-mode). The package needs to be simply evaluated. It's a single .el file. That's it.

If you could please tell me how to do it that would save me literal hours!

I'm using doom emacs, which has a wrapper macro:
````
(package! htmlz-mode
  :recipe (:host github :repo "0xekez/htmlz-mode"))
````

This doesn't work. This doesn't tell you why it doesn't work. This consumes your very essence of being... (no logs, no warnings, nothing...)

If someone could please point me how to debug this type of problems that would be probably even better, because there is NO documentation as of 2023.

**Comment by progfolio** [comment]
Please see the explanation I gave here: https://github.com/radian-software/straight.el/issues/1091#issuecomment-1560186384

I understand you are frustrated, but please refrain from opening multiple issues and using them to voice your frustrations.
