### ISSUE TITLE
Straight.el doesn't give any errors when package isn't being loaded

### ISSUE THREAD

**Issue by danielkrajnik** [radian-software/straight.el#1092]
Installing [htmlz-mode](https://github.com/0xekez/htmlz-mode) didn't give any warnings that it wasn't loaded correctly, which is a nightmare to debug.

There should be warning like - package doesn't have appropriate headers - another reason why emacs is so overly complicate and unapproachable.

Otherwise I love straight.el...

**Comment by progfolio** [comment]
Straight does not load packages. Please see the comment in the other, related issue: https://github.com/radian-software/straight.el/issues/1091#issuecomment-1560186384
