### ISSUE TITLE
How to contribute to a package when the recipe is from a mirror?

### ISSUE THREAD

**Issue by doolio** [radian-software/straight.el#1099]
I raised a bug on the `denote` package which is developed on [sourcehut](https://git.sr.ht/~protesilaos/denote). The author responded with an email patch for me to test. Before testing I want to ensure I'm running the latest version of the package. However, `straight` retrieves this package from its own mirror of GNU ELPA so the commit history is different. The commit history on the `emacs-straight` mirror does give details of the corresponding commit on GNU ELPA and Emacs (unsure what that means, emacs.git perhaps?) respectively. However, the last commit on the `emacs-straight` mirror at the time of writing combines the last two commits from sourcehut.

All this may not be an issue but how do I contribute to this or another package where `straight` retrieves the package from `emacs-straight` rather than from the source of development?

Thanks for `straight` and your time.

**Comment by raxod502** [comment]
You'd want to adjust the recipe for your package to fetch directly from Sourcehut, and then do a hard reset (or normalize the package, I think that would accomplish the same). Normally, `straight.el` would pull from upstream, but if it is falling through to the mirror, then that means the source location hasn't been published anywhere (e.g. on MELPA), and `straight.el` has no way of knowing the location.

**Comment by doolio** [comment]
> You'd want to adjust the recipe for your package to fetch directly from Sourcehut, and then do a hard reset (or normalize the package, I think that would accomplish the same). 

OK, that makes sense. However, another package from the same author [modus-themes](https://git.sr.ht/~protesilaos/modus-themes) also developed on sourcehut returns the following recipe and I made no change to it. I can see the upstream history in its local repository as well.

```
(modus-themes :type git :flavor melpa :host sourcehut :repo "protesilaos/modus-themes")
```

which suggests it is still packaged for MELPA. It can also be found on GNU ELPA. 

In contrast the recipe (for me) for denote is as follows:

```
(denote :type git :host github :repo "emacs-straight/denote" :files ("*" (:exclude ".git")))
```

I cannot find `denote` on MELPA but only on GNU ELPA. Not sure why it is packaged for one and not the other.

Also, to be clear by a hard reset you mean to delete the package repo and build directories, right?

**Comment by raxod502** [comment]
Whether the package is on MELPA is up to its author. Some people don't want to publish there, for some reason. In my opinion, that introduces difficulties which could be avoided if we standardized, but it is not my choice to make.

I was referring to using Git commands to change the remote and performing a `git reset --hard`. Or you can use `M-x straight-normalize-package`.
