### ISSUE TITLE
Can `:straight` `use-package` integration defer the packages when I need it? 

### ISSUE THREAD

**Issue by ccqpein** [radian-software/straight.el#1101]
I have some package load with `use-package` and `straight.el` integration. Like: 

```lisp
(use-package ejira
  :straight (ejira :type git :host github :repo "nyyManni/ejira"))
```

`ejira` need to require the org mode, so everytime I restart my emacs (even not open the `.org` file), org-mode will load. 

And I test some other packages I load inside `use-package` through `straight.el`. Looks like `:straight` keyword will check the package everytime I start emacs even it should be defer. Is there some way that `:straight` keyword check the package only this mode is loading? 

Thanks!

**Comment by progfolio** [comment]
> Looks like :straight keyword will check the package everytime I start emacs even it should be defer. Is there some way that :straight keyword check the package only this mode is loading?

use-package loads packages, straight.el only prepares them to be loaded ("activates" packages). Please see the use-package documentation:

https://jwiegley.github.io/use-package/keywords/

> :defer, :demand
> 
> In almost all cases you don’t need to manually specify :defer t. This is implied whenever :bind or :mode or :interpreter is used. Typically, you only need to specify :defer if you know for a fact that some other package will do something to cause your package to load at the appropriate time, and thus you would like to defer loading even though use-package isn’t creating any autoloads for you.
> 
> You can override package deferral with the :demand keyword. Thus, even if you use :bind, using :demand will force loading to occur immediately and not establish an autoload for the bound key. 


Unless you have a keyword which defers the package, or set `use-package-always-demand` non-nil, the declaration your provided will require the `ejira` feature. The following will prevent the package from being required immediately:

```emacs-lisp
(use-package ejira
  :straight (ejira :type git :host github :repo "nyyManni/ejira")
  :defer t)
```

**Comment by ccqpein** [comment]
Thanks for your reply @progfolio . 

I played around a bit. And I print out the `rest` arguments in `straight-use-package--straight-handler` function. And it shows the org-mode has the `:defer t` but the `ejira` doesn't have the `:defer` keyword. 

I think you are right, for some reason, the `use-package` doesn't give the `defer t` to `ejira`. I manually add the `:defer t` just as same as your upper code. It loads failed when I open org file when `org-mode` has hooks with `ejira`. I am trying to change `ejira` now. And I think you can close this issue. Sorry about that. Thanks again.

**Comment by progfolio** [comment]
No problem. Good luck with it.
