### ISSUE TITLE
are bitcoin-address-validation.{hs,java} OK?

### ISSUE THREAD

**Issue by samcramer** [radian-software/straight.el#1102]
Microsoft Defender identifies ../test/data/rosetta/{haskell,java}/bitcoin-address-validation.{hs,java} as possible threats.  Are they?  If they are, why is the rosetta blockchain integration program needed by straight.el.

Screenshot:

![ms-defender-straight-el-warning](https://github.com/radian-software/straight.el/assets/6877655/f214528f-2945-4e7b-ab61-b6fbd0287117)

**Comment by progfolio** [comment]
> Microsoft Defender identifies ../test/data/rosetta/{haskell,java}/bitcoin-address-validation.{hs,java} as possible threats. Are they? 
>  [W]hy is the rosetta blockchain integration program needed by straight.el.

That was installed as a dependency of  "language-detection.el". It's not a dependency of straight.el itself.
You'll want to take askthe language-detection.el maintainer:

https://github.com/andreasjansson/language-detection.el
