### ISSUE TITLE
Package behaving differently when loaded with straight-use-package

### ISSUE THREAD

**Issue by yPhil-gh** [radian-software/straight.el#1103]
## What's wrong

When the [gpt4emacs](https://framagit.org/yphil/gpt4emacs) package is loaded using the `load` function, the Emacs built-in `url-retrieve` function behaves as expected. However, when said gpt4emacs package is loaded using use-package and straight, the API responds by asking for credentials, even though the same API key is provided.

Additionally, I don't seem to figure out how to tell Straight (or Quelpa, read on) to not build the package, on the off-chance that this would work around the problem.

EDIT When I byte-compile and `load-library` the file, everything works.
EDIT2 I tried [Quelpa](https://github.com/quelpa/) (always with blank init file) and the problem is the same :disappointed: 

## Directions to reproduce

1. Start with an empty init file.
2. Add the bootstrap snippet for straight.el to your init file:

``` emacs-lisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

```

3. Add the following code to your init file to install and configure `use-package` and `gpt4emacs`:

``` emacs-lisp
    (setq straight-use-package-by-default t)
    (straight-use-package 'use-package)

    (use-package gpt4emacs
      :straight (gpt4emacs
                 :type git
                 :repo "https://framagit.org/yphil/gpt4emacs.git"))
```
4. Start Emacs.
5. Use `M-x customize-variable RET gpt-api-key-file` to point to a file with only your API key.
6. Observe that the API responds by asking for a "Username" when `url-retrieve` is calling it.

7. instead of the straight / use-package declarations, simply load the module like this:
``` emacs-lisp
(load "~/src/lisp/gpt4emacs/gpt4emacs.el")
```
or even the straight repo package
``` emacs-lisp
(load "~/.config/emacs/straight/repos/gpt4emacs/gpt4emacs.el")
``` 

The url-retrieve fct behaves normally.

If I then try to load the straight-built package like this:
``` emacs-lisp
(load "~/.config/emacs/straight/build/gpt4emacs/gpt4emacs.elc")
``` 
Then the url-retrieve behave _**differently**_, and the API asks for credentials :frowning: 

:arrow_forward:  It also works fine when visiting `gpt4emacs.el `in a buffer and `eval-buffer`'ing it, which seem to be in contradiction with the straight documentation..?

I'm messaging the API key right before the `url-retrieve`, and in _both_ cases it it properly set.

### Version information

* Emacs version: GNU Emacs 28.2 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
* Operating system: GNU/Linux Ubuntu 22.04.2 LTS

**Comment by progfolio** [comment]
This sounds like an upstream issue with the package.
It looks like  you are the package author as well.
The help-gnu-emacs mailing list, reddit.com/r/emacs/, the #emacs IRC channel, or the Emacs stack exchange site are good resources to ask questions about authoring elisp packages.
