### ISSUE TITLE
RFI: use-package and system repo

### ISSUE THREAD

**Issue by rileyrg** [radian-software/straight.el#1105]
I've migrated to hand built emacs 29 which includes eglot. I would like to still use stright/use-package but when I 

`(use-package eglot... )`

it's cloning it. Ive browsed through the docs but cant seem to pinpoint what I need to set to stop it cloning if there is a local repo. I obviously dont want to hard code a recipe  pointing to emacs 29 elisp files if at all avoidable.

**Comment by progfolio** [comment]
Hi. Thanks for taking the time to fill out a support ticket.
Please see the following:

https://github.com/radian-software/straight.el#how-can-i-use-the-built-in-version-of-a-package

Does that help?

**Comment by rileyrg** [comment]
I totally missed that Nicholas. Thank you. It worked as desired. Would that fall back to straight installing it if the library didnt exist I wonder? eg if I had to move back to emacs 28 (which I wont:)).

**Comment by rileyrg** [comment]
Fantastic. I'm trying to manipulate that into the (use-package :straight ...) form referenced above. I shall keep at it - I need to blow the cobwebs away.

**Comment by rileyrg** [comment]
The use-package equivalent:

**Comment by rileyrg** [comment]
The use-package equivalent from my config. Using a permalink as I can't get elisp embedding properly.

[use-package using system libraries based on Emacs version.](https://github.com/rileyrg/Emacs-Customisations/blob/85563ec5efb294a4434a343b10c6c820c69dee48/etc/elisp/rgr-lsp.el)

**Comment by progfolio** [comment]
```emacs-lisp
(eval `(use-package eglot ,@(when (>= emacs-major-version 29) '(:straight (:type built-in)))
  :config
  (use-package eldoc-box)
  :hook
  (prog-mode . eglot-ensure)
  (prog-mode . eldoc-box-hover-mode)
  :bind
  (:map flymake-mode-map
        ([remap next-error] . flymake-goto-next-error)
        ([remap previous-error] . flymake-goto-prev-error))
  (:map eglot-mode-map
        ("<M-return>" . eglot-code-actions))))
```

You shouldn't need to `eval` the declaration.
The `:straight` keyword can handle the backquoted list as well. e.g.


```emacs-lisp
(use-package eglot
  :straight `(eglot ,@(when (>= emacs-major-version 29) (:type built-in))))
```

Should roughly expand to:

```emacs-lisp
(progn
  (straight-use-package
   `(eglot ,@(when (>= emacs-major-version 29) (:type built-in))))
  (require 'eglot nil nil))
```

**Comment by rileyrg** [comment]
Unfortunately that doesn't work. 

> Debugger entered--Lisp error: (void-function :type)
>   (:type built-in)
>   (progn (:type built-in))
>   (if (>= emacs-major-version 29) (progn (:type built-in)))
>   (cons 'eglot (if (>= emacs-major-version 29) (progn (:type built-in))))
>   (straight-use-package (cons 'eglot (if (>= emacs-major-version 29) (progn (:type built-in)))))
>   (progn (straight-use-package (cons 'eglot (if (>= emacs-major-version 29) (progn (:type built-in))))) (defvar use-package--warning105 #'(lambda (keyword err) (let ((msg (format "%s/%s: %s" ... keyword ...))) (display-warning 'use-package msg :error)))) (condition-case err (if (not (require 'eglot nil t)) (display-warning 'use-package (format "Cannot load %s" 'eglot) :error)) ((debug error) (funcall use-package--warning105 :catch err))))
>   elisp--eval-last-sexp(nil)
>   eval-last-sexp(nil)
>   funcall-interactively(eval-last-sexp nil)
>   command-execute(eval-last-sexp)

**Comment by progfolio** [comment]
Apologies, that was a typo on my phone. The list to splice in needs to be quoted.

```emacs-lisp
(use-package eglot
  :straight `(eglot ,@(when (>= emacs-major-version 29) '(:type built-in))))
```
