### ISSUE TITLE
Emacs When Using With straight.el Complains About void Symbol’s value `inherit`

### ISSUE THREAD

**Issue by mehdikhawari** [radian-software/straight.el#1106]
## What's wrong

I use straight.el as package manager, and I'd like to use the [cursory ](https://github.com/protesilaos/cursory/) package.

When evaluating the following lines
``` emacs-lisp
(use-package cursory
  :demand t)
```
I see the following warnings in straight-byte-compilation buffer.
```
cursory.el:262:35: Warning: `(inherit (plist-get (alist-get preset
    cursory-presets) :inherit))' is a malformed function
cursory.el:262:35: Warning: Unused lexical argument `preset'
cursory.el:265:34: Warning: reference to free variable `inherit'

In end of data:
cursory.el:264:4: Warning: the function `when-let*' might not be defined at
    runtime.
```
When doing `M-x cursory-set-preset` and choosing a preset, I get this error message:
`cursory--get-preset-properties: Symbol’s value as variable is void: inherit`. The package is unusable.

In `emacs -Q` I can use this package without any problem.

Do I miss something?

### Test

<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :user-dir "test-cursory"
  :post-bootstrap 
  (straight-use-package 'cursory)
  (cursory-set-preset 'bar))
```
</details>

- Test run at: `2023-08-01 11:44:29`
- system-type: `windows-nt`
- straight-version: `prerelease (HEAD -> master, origin/master, origin/HEAD) ff63b15 2023-06-15`
- emacs-version: `GNU Emacs 28.2 (build 2, x86_64-w64-mingw32)
 of 2022-09-13`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done

Test run with version: prerelease (HEAD -> develop, origin/develop) b08ed0e 2023-07-19

Packages:
"straight"                n/a                  develop b08ed0e 2023-07-19
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 4d9ff971 2023-07-30
"gnu-elpa-mirror"         n/a                  master be1351c 2023-07-14
"nongnu-elpa"             n/a                  main c0840d0 2023-06-28
"el-get"                  melpa                master f3f1edd4 2023-07-25
"emacsmirror-mirror"      n/a                  master cd860df 2023-07-31
"cursory"                 gnu-elpa-mirror      master f7eddae 2023-07-09

Error: (void-variable inherit)
Looking for gnu-elpa-mirror recipe -> Cloning melpa...
Looking for gnu-elpa-mirror recipe -> Cloning melpa...done
Looking for nongnu-elpa recipe -> Cloning gnu-elpa-mirror...
Looking for nongnu-elpa recipe -> Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe -> Cloning nongnu-elpa...
Looking for emacsmirror-mirror recipe -> Cloning nongnu-elpa...done
Looking for emacsmirror-mirror recipe -> Cloning el-get...
Looking for emacsmirror-mirror recipe -> Cloning el-get...done
Looking for straight recipe -> Cloning emacsmirror-mirror...
Looking for straight recipe -> Cloning emacsmirror-mirror...done
Building straight...
Building straight...done
Cloning cursory...
Cloning cursory...done
Building cursory...
Building cursory...done

```
</details>
### Version information

* Emacs version: GNU Emacs 28.2 (build 2, x86_64-w64-mingw32) of 2022-09-13
* Operating system: Windows 10 & FreeBSD 13.2

**Comment by progfolio** [comment]
> ```
> cursory.el:262:35: Warning: `(inherit (plist-get (alist-get preset
>     cursory-presets) :inherit))' is a malformed function
> cursory.el:262:35: Warning: Unused lexical argument `preset'
> cursory.el:265:34: Warning: reference to free variable `inherit'
> 
> In end of data:
> cursory.el:264:4: Warning: the function `when-let*' might not be defined at
>     runtime.
> ```

These byte-compilation errors point to a bug in the package.
cursory.el does not require subr (or subr-x for older versions of Emacs) at compile time.
Please report this as a bug with cursory's package maintainer.
