### ISSUE TITLE
How to debug why a package is not being compiled

### ISSUE THREAD

**Issue by LemonBreezes** [radian-software/straight.el#1112]
Hello. I am working on https://github.com/zwild/eshell-prompt-extras and Straight is not compiling this package at all but the package compiles on my Emacs instance without any warnings (on my enable-lexical-binding branch in my PR). How do I figure out why it's not being compiled?

**Comment by progfolio** [comment]
Hi. Please include the output of `M-x straight-version` and show the code you are using to install the package.

**Comment by progfolio** [comment]
You can also try evaluating the following test case to rule out your configuration.
The package compiles on my end:


<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :post-bootstrap
  (straight-use-package 'eshell-prompt-extras)
  (message "%S"
           (directory-files-recursively
            (straight--build-dir "eshell-prompt-extras") "elc$" 'include-dirs)))
```
</details>

- Test run at: `2023-08-14 09:13:44`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> develop, origin/develop) 9b11112 2023-08-08`
- emacs-version: `GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8)
 of 2023-08-09`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 9b11112 2023-08-08
Cloning eshell-prompt-extras...
Cloning eshell-prompt-extras...done
Building eshell-prompt-extras...
Building eshell-prompt-extras...done

("/tmp/straight.el-test-xXof8j/straight/build/eshell-prompt-extras/eshell-prompt-extras.elc")
Packages:
"straight"                n/a                  develop 9b11112 2023-08-08
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master c1c9cb39 2023-08-14
"gnu-elpa-mirror"         n/a                  master b97c2f4 2023-08-13
"nongnu-elpa"             n/a                  main 14e9631 2023-08-08
"el-get"                  melpa                master e1a3e59d 2023-08-13
"emacsmirror-mirror"      n/a                  master 8e7cbfe 2023-08-07
"eshell-prompt-extras"    melpa                master d904bab 2023-08-10


```
</details>

I would also check what `straight-get-recipe` returns for that package.

**Comment by LemonBreezes** [comment]
> 

On my computer that also works. I think this is a problem with `doom-emacs`.

**Comment by raxod502** [comment]
@progfolio - this might be a good opportunity for us to add to the logging framework (e.g., details about when packages are compiled). Issues arising with Doom Emacs have been a persistent problem because the gap between our environment and theirs is so large. But if we just ask people to upgrade to the latest `straight.el` and enable logging, we could get more details without having to run Doom.

**Comment by LemonBreezes** [comment]
By the way, I just deleted my `straight` folder and re-installed all my packages and everything was correctly compiled! I have no idea why it happened, but next time I'll try just re-installing all the packages.
