### ISSUE TITLE
I cannot install magit

### ISSUE THREAD

**Issue by dnadales** [radian-software/straight.el#1113]
I have the following configuration:

```elisp
(straight-use-package 'magit
		      :ensure t)
```

This command does not install `magit` but does not give an error either.

I've tried `M-x straight-use-package` and `magit` is not among the list of candidates.

What am I missing?

**Comment by progfolio** [comment]
What is the output of `M-x straight-version`?

**Comment by dnadales** [comment]
Sorry, I should have included that:

```text
prerelease (HEAD -> master, origin/master, origin/HEAD) ff63b15 2023-06-15
```

Also:

```text
GNU Emacs 29.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2023-08-04
```

**Comment by progfolio** [comment]
This is not the correct syntax:

 ```emacs-lisp
 (straight-use-package 'magit :ensure t)
 ```

`straight-use-package`'s function signature is:

```emacs-lisp
(straight-use-package MELPA-STYLE-RECIPE &optional NO-CLONE NO-BUILD CAUSE
INTERACTIVE)
```

And so `:ensure` is being interpreted as a non-nil `NO-CLONE` argument, and `t` is being interpreted as `NO-BUILD`.
`:ensure` is a use-package keyword, but it is not necessary when using straight's use-package integration.
The correct form should be:

```emacs-lisp
(straight-use-package 'magit)
```

**Comment by dnadales** [comment]
That was the problem indeed. Thank you!
