### ISSUE TITLE
Can you add changes to upstream packages locally?

### ISSUE THREAD

**Issue by danielkrajnik** [radian-software/straight.el#1119]
I'm using doom framework and it's not clear whether this is doom or straight.el behavior? When I'm adding patches to package files (e.g. htmlz-mode in `$HOME/.config/emacs/.local/straight/repos/htmlz-mode/htmlz.el` and adding these changes to the local .git database (e.g. `git commit -am "fix htmlz-mode not showing up on start"`) the next time I'm updating doom (`doom upgrade`) it destroys that git history - only local commits remain and upstream changes history is gone. This breaks the package completely.

What I was hoping to achieve is editing non-critical upstream packages. Is this something that straight.el support?

**Comment by progfolio** [comment]
straight.el should prompt you for what you'd like to do. It won't silently discard any commits or the worktree when updating. Sounds like behavior `doom` has built on top of straight.

**Comment by danielkrajnik** [comment]
thank you for confirming. If I'll have to spend a week migrating to vanilla emacs it's helpful to learn that it won't be for nothing.

**Comment by danielkrajnik** [comment]
Sorry, just to confirm, it's a bit vague, but when adding local patches to upstream packages is there anything that you think might cause issues to the user any other problems than potential merge conflicts?

**Comment by raxod502** [comment]
`straight.el` will allow you to run whatever revision you want. There is no limitation built in to the framework. The issues would come from if the behavior does not match user expectations.
