### ISSUE TITLE
Problem moving straight directory after update

### ISSUE THREAD

**Issue by nivaca** [radian-software/straight.el#1120]
This issue has just begun after updating my config. (I was on bookstrap-version 5 and moved up to 6; don't know if that's important.)

I need to have my `straight/` directory inside my `~/.emacs.d/` (as I share my main Emacs config with other machines using Dropbox, which is syncing my main emacs directory, `~/Dropbox/emacs/`).

Before this, I had this line in my bootstrap code, which used to work:

```elisp
(setq straight-base-dir (expand-file-name "~/.emacs.d"))
```

However, the straight directory is now deployed in my main emacs directory (`~/Dropbox/emacs/`).

Is there any way to revert this issue?

I'm running GNU Emacs 29.1 (build 1, x86_64-redhat-linux-gnu, GTK+ Version
 3.24.38, cairo version 1.17.8) of 2023-07-27
On Fedora Linux 28.

Thanks!

**Comment by progfolio** [comment]
Is "~/.emacs.d/" a symlink?

**Comment by nivaca** [comment]
No, just the real directory.

**Comment by progfolio** [comment]
Please link to or share your configuration.

**Comment by nivaca** [comment]
It's here:
https://raw.githubusercontent.com/nivaca/emacsconf/main/mylisp/mypackages.el
Notice that I had to comment lines 6-7 to avoid error messages.

**Comment by progfolio** [comment]
> It's here: https://raw.githubusercontent.com/nivaca/emacsconf/main/mylisp/mypackages.el Notice that I had to comment lines 6-7 to avoid error messages.

What are the error messages?

**Comment by nivaca** [comment]
OK. When I uncomment both lines, I get no error, but the `straight` directory is created inside my `~/emacs` directory (which is actually symlinked), which I don't want.
But when I have the two following lines:

```elisp
(setq straight-base-dir (expand-file-name "~/.emacs.d"))
(setq straight-build-dir (expand-file-name "~/.emacs.d"))
```

I get the following error:

`File is missing: Cannot open load file, No such file or directory, /home/nivaca/emacs/straight/repos/straight.el/bootstrap.el`

**Comment by raxod502** [comment]
Get rid of the `straight-build-dir` setting; that almost certainly doesn't do what you want.

For `straight-base-dir`, try https://github.com/radian-software/straight.el/pull/1123.

**Comment by nivaca** [comment]
Ok, I have this in my init:

```lisp
(setq straight-base-dir (expand-file-name "~/.emacs.d"))

;; Bootstrap straight.el ----------------------------
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
;; ---------------------------------------------------
```

And I get this error when launching Emacs:

`File is missing: Cannot open load file, No such file or directory, /home/user/emacs/straight/repos/straight.el/bootstrap.el`

Any ideas on what's going on? 
Thanks.

**Comment by raxod502** [comment]
You need to use the bootstrap snippet from https://github.com/radian-software/straight.el/pull/1123/files.

**Comment by nivaca** [comment]
Thanks. That did the trick.
