### ISSUE TITLE
Magit is complaining that it needs a later version of transient

### ISSUE THREAD

**Issue by eamonnsullivan** [radian-software/straight.el#1139]
After pulling the latest recently, magit has started displaying the following warning message (see below). I've done what the warning says about setting that variable, but the rest seems geared toward users of 'package'. 
```
Emergency (magit): Magit requires ‘transient’ >= 0.5.0,
but due to bad defaults, Emacs’ package manager, refuses to
upgrade this and other built-in packages to higher releases
from GNU Elpa.

To fix this, you have to add this to your init file:

  (setq package-install-upgrade-built-in t)

Then evaluate that expression by placing the cursor after it
and typing C-x C-e.

Once you have done that, you have to explicitly upgrade ‘transient’:

  M-x package-upgrade transient \‘RET’

Then you also must make sure the updated version is loaded,
by evaluating this form:

  (progn (unload-feature ’transient t) (require ’transient))

If you don’t use the ‘package’ package manager but still get
this warning, then your chosen package manager likely has a
similar defect. Disable showing Disable logging
```
 I'm using `GNU Emacs 28.2 (build 2, aarch64-apple-darwin22.1.0, NS appkit-2299.00 Version 13.0 (Build 22A8380))
 of 2023-04-27` and I've tried adding `(use-package transient)`. I've also tried adding transient to the list in `straight-recipes-gnu-elpa-ignored-packages`, but the warning remains. This probably isn't a bug, but rather a misunderstanding on my part about how to get the latest packages.

**Comment by progfolio** [comment]
> I've done what the warning says about setting that variable, but the rest seems geared toward users of 'package'.

That variable is also for users of package.el.

Please include the output of: `M-x straight-version`, `M-x locate-library transient`, and `M-x straight-get-recipe transient`.

**Comment by eamonnsullivan** [comment]
straight-version: `prerelease (HEAD -> develop, origin/master, origin/develop, origin/HEAD) b3760f5 2023-10-21`
locate-library transient: `Library is file ~/.config/emacs/straight/build/transient/transient.el`
straight-get-recipe transient: `(transient :type git :flavor melpa :host github :repo "magit/transient")`

**Comment by eamonnsullivan** [comment]
In fact, the CHANGELOG in that library location suggests I'm using v0.5.3 of transient, so perhaps the issue is that Magit is displaying that warning in error.

**Comment by eamonnsullivan** [comment]
I've opened https://github.com/magit/magit/issues/5069

**Comment by eamonnsullivan** [comment]
Sorry for the bother. Happy Christmas!

**Comment by progfolio** [comment]
You'll want to hoist the form which installs seq before the one which installs magit. e.g.

```emacs-lisp
(straight-use-package 'seq)
(straight-use-package 'magit)
```

**Comment by eamonnsullivan** [comment]
I did that, inserting it just before my `(use-package magit)` and I'm still getting the warning.

**Comment by eamonnsullivan** [comment]
What *did* work was to just load magit among the first things in my init, above a bunch of other things. That seems to have done the trick. Some race condition in loading modules, I guess. Thank you. Happy Christmas!

**Comment by defaultxr** [comment]
> What did work was to just load magit among the first things in my init, above a bunch of other things. That seems to have done the trick. Some race condition in loading modules, I guess. Thank you. Happy Christmas!

For me it seems to have been [Combobulate](https://github.com/mickeynp/combobulate). Removing it from my init.el stopped Magit from complaining.
