### ISSUE TITLE
Loading bootstrap.el takes 2s

### ISSUE THREAD

**Issue by FabriceSalvaire** [radian-software/straight.el#1143]
Using Emacs 29
`.../eln-cache/29.2-623ad7f7/straight-1c0f67b7-71eaf850.eln`

```
**Messages**

* 0.389704::before straight bootstrap
* 0.391497::load straight.el
Loading .../straight/repos/straight.el/bootstrap.el (source)...done
* 2.738980::after straight bootstrap
```

Any clue ?
Doom setup doesn't have this issue.

**Comment by FabriceSalvaire** [comment]
Found `(setq straight-check-for-modifications nil)` solve this issue.

Maybe you could enhance that in this large README:

> [straight-check-for-modifications](https://github.com/radian-software/straight.el#customizing-when-packages-are-built) -- to configure an alternate way for straight.el to check for modifications made to package source code, rather than the default (which is 100% reliable, but has a minor cost to startup time).

**Comment by progfolio** [comment]
> Maybe you could enhance that in this large README:

I've added your suggestion to the issue we have for documentation improvements. Thanks.

**Comment by raxod502** [comment]
Well. I don't know that I would recommend disabling modification checking entirely, but if you want, that's a viable option. I would rather suggest setting up the filesystem watcher, which is what I do. It has almost no startup performance penalty.
