### ISSUE TITLE
sunrise-commander should use currently maintained repo

### ISSUE THREAD

**Issue by dadinn** [radian-software/straight.el#1155]
The `sunrise-commander` package still references the unmaintained [escherdragon repository](https://github.com/escherdragon/sunrise-commander).

Instead the currently maintained version can be found [here](https://github.com/sunrise-commander/sunrise-commander).

**Comment by raxod502** [comment]
straight.el does not maintain package recipes, you should report this to the relevant registry. I checked my local installation and it is using sunrise-commander/sunrise-commander, so you probably have out-of-date recipe repositories.
