### ISSUE TITLE
Clarification on `:if` and `:when` behavior

### ISSUE THREAD

**Issue by Arian-D** [radian-software/straight.el#1157]
Hi,

My config is a collection of `(use-package ...)` statements, and in most of them I use `:when` for loading a package under certain conditions. For instance, I have the following block in my config
```elisp
(use-package geiser-guile
    :when (executable-find "guile")
    :after geiser)
```
and I have `straight-use-package-by-default` set to `t`. My (previous) understanding was that the `:when` would prevent `geiser-guile` from being cloned if I didn't have Guile on my path (similar to `:disabled`), but that doesn't seem to be the case; `(macroexpand '(use-package abc :if (= 1 2)))` reveals that the condition is used *after* `straight-use-package` is called.

It's not a request to change it, and I just wanted to know if that is intentional. If it is, I'll just do something like `(when (= 1 2) (use-package ...))` in my config.

Thank you.

**Comment by raxod502** [comment]
I think https://github.com/radian-software/straight.el/pull/1158 should clarify this, does it answer the question adequately? Sorry for the delay.

**Comment by Arian-D** [comment]
I forgot to close this.

It absolutely does address my question!  I very much appreciate the explanation, and I will most likely use your `radian-use-package` macro.

**Comment by progfolio** [comment]
-------- Original message --------From: Arian Dehghani ***@***.***> Date: 5/2/24  6:11 PM  (GMT-05:00) To: "radian-software/straight.el" ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [radian-software/straight.el] Clarification on `:if` and `:when` behavior (Issue #1157) 
I forgot to close this.
It absolutely does address my question!  I very much appreciate the explanation, and I will most likely use your radian-use-package macro.
