### ISSUE TITLE
Conditional byte-compilation fails to build the package

### ISSUE THREAD

**Issue by divyaranjan1905** [radian-software/straight.el#1163]
## What's wrong
When I try to use conditional byte-compilation in the `:build` keyword, the package isn't built at all.

## Directions to reproduce
 After a successful bootstrap, the following doesn't create a build in `straight/build/` under `user-emacs-directory`:

```
(use-package package-name
    :straight t
    :build (:no compile))
```

While what should've happened is that there would be a folder `package-name` under `straight/build` which would build the package without byte-compiling it. The repo doesn't even get cloned, as there is nothing in `straight/repos/` either.

Removing that particular line for `:build` keyword builds the package as usual, but with byte-compilation. I want to disable it for a particular package.

### Version information

* Emacs version:
GNU Emacs 30.0.50
Development version d7071359522f on master branch; build date 2024-03-11.
Copyright (C) 2024 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

* Operating system:
Arch Linux, with kernel 6.7.0.6

**Comment by progfolio** [comment]
How about if  `:no`  is substituted with `:not`?

**Comment by divyaranjan1905** [comment]
That works, thank you!
