### ISSUE TITLE
packaging of auctex

### ISSUE THREAD

**Issue by wang1zhen** [radian-software/straight.el#1165]
## What's wrong

The packaging of [auctex](https://github.com/emacs-straight/auctex) has been changed and `tex-site.el` was replaced by `tex-sit.el.in`. As there is no process of `make`, the `tex-site.el` will be missing, and makes auctex unusable.

## Directions to reproduce

`(straight-pull-package 'auctex)`

### Version information

* Emacs version: emacs 29.4
* Operating system: Arch linux

**Comment by VictorYYW** [comment]
The same issue occurred to me. It looks like `tex-site.el` somehow get included in `.gitignore` upstream. And the change is mirrored into `emacs-straight/auctex`. My workaround is to checking out the [previous commit ](https://github.com/emacs-straight/auctex/commit/2825e44244f99206c8c247360d61cc8464c0076d) and rebuild `auctex`.

**Comment by jezcope** [comment]
I've just got it working with the following `:pre-build` option to regenerate `tex-site.el` before straight does its build process:

```emacs-lisp
(use-package tex-site
  :straight (auctex :type git
		    :host github
		    :repo "emacs-straight/auctex"
		    :files ("*" (:exclude ".git"))
		    :pre-build ("make" "tex-site.el")))
```

**Comment by wang1zhen** [comment]
it seemed fix now, closing this issue.
