### ISSUE TITLE
Timeouts on git.savannah.gnu.org. Unable to bootstrap my configuration

### ISSUE THREAD

**Issue by SeungheonOh** [radian-software/straight.el#1171]
I'm getting 
```
$ cd /home/sho/.emacs.d/straight/repos/
$ git clone --origin origin --no-checkout https\://git.savannah.gnu.org/git/emacs/nongnu.git /home/sho/.emacs.d/straight/repos/nongnu-elpa/ --single-branch

Cloning into '/home/sho/.emacs.d/straight/repos/nongnu-elpa'...
fatal: unable to access 'https://git.savannah.gnu.org/git/emacs/nongnu.git/': Failed to connect to git.savannah.gnu.org port 443 after 135866 ms: Could not connect to server
```

After brief research it seems that gnu.org is down for few month now. Is there a way to install straight.el without using gnu package repositories?

**Comment by progfolio** [comment]
> After brief research it seems that gnu.org is down for few month now

There have been several intermittent outages, but it has been up the majority of the time.
Here is where the FSF posts out of band updates:

https://hostux.social/@fsfstatus

As you can see, they've had a data center issue recently.
It's already being resolved.

> Is there a way to install straight.el without using gnu package repositories?

That would involve addressing this:

https://github.com/radian-software/straight.el/blob/88e574ae75344e39b436f863ef0344135c7b6517/bootstrap.el#L109-L154

**Comment by SeungheonOh** [comment]
Thanks, it's been back again I can confirm now. I ended up just rsync-ed my config folder from my other machine which worked like a charm.

**Comment by darosio** [comment]
It seems to be again unreachable today. Is anyone else having issues?

**Comment by progfolio** [comment]
> It seems to be again unreachable today. Is anyone else having issues?

Temporary networking issues are bound to crop up from time to time.
There's not much we can do here about that.
Instead of bumping a closed issue, a better resource will be the FSF's out of band announcements:

https://hostux.social/@fsfstatus
