### ISSUE TITLE
Support for NonGNU ELPA?

### ISSUE THREAD

**Issue by aspiers** [radian-software/straight.el#762]
I'm trying to figure out how to use [NonGNU ELPA](https://elpa.nongnu.org/) packages from `straight.el`, and it doesn't seem particularly obvious.  Actually, maybe it's not even easy or possible without further development, since:

- for GNU ELPA support, the https://github.com/emacs-straight mirror is required
- there are dedicated backends for GNU ELPA / Org ELPA, with code such as `straight-recipes-gnu-elpa-retrieve`
- there is no such backend for other ELPA repositories

Currently [there are only 6 packages in NonGNU ELPA](https://elpa.nongnu.org/nongnu/), but at least two of them are probably fairly popular packages:

- `org-contrib`, which has been recently removed from Org master branch and will not be distributed within the upcoming Org 9.5 release
- `markdown-mode`

and I expect this list to grow over time.  So it would be great if it was easy to access these via `straight.el`.

Even if the maintainers don't have time to add support for this soon, if any hints could be shared here on the rough approach then maybe I or someone else will find time to follow those hints at a later date.  This reminds me of #686 ("Confused about mirroring of GNU ELPA packages"), the resolution of which might help with understanding how to solve this issue.

**Comment by progfolio** [comment]
So long as the build machinery for NonGNU ELPA is similar to GNU ELPA,
it shouldn't bee hard to implement support. In general, adding support for a recipe repository
boils down to implementing an interface for it described here:

https://github.com/raxod502/straight.el/tree/develop#where-do-recipes-come-from

The gnu-elpa implementation is here:

https://github.com/raxod502/straight.el/blob/e46292db6910e8e7701d53acaf188de0101ae30f/straight.el#L3151-L3244

If there is scignificant overlap between GNU/NonGNU ELPA (which I suspect there may be) we could probably refactor
so that the two recipe repository back ends could share code.

**Comment by raxod502** [comment]
Well. It basically comes down to how ridiculous the build system is. If GNU ELPA used something reasonable like MELPA did, then we wouldn't have any problem at all. But unfortunately, the GNU ELPA build system is such a gigantic mess that it's basically impractical to run yourself, so I had to create https://github.com/raxod502/gnu-elpa-mirror.

So depending on how NonGNU ELPA is set up, we might have to extend GNU ELPA Mirror to mirror the packages from there as well.

If you want to experiment with trying to install NonGNU ELPA packages in `straight.el`, you don't have to implement a recipe repository backend. All those do is automatically generate recipes for the packages in the repository. But you can achieve the same result by simply providing a recipe for a package yourself.

**Comment by aspiers** [comment]
For the record, the following seems to work fine:

```elisp
(use-package org-plus-contrib
  :straight (:type git :repo "https://git.sr.ht/~bzg/org-contrib"))
```

**Comment by progfolio** [comment]
That expands to:

```emacs-lisp
(progn
  (straight-use-package
   '(org-plus-contrib :type git :repo "https://git.sr.ht/~bzg/org-contrib"))
  (require 'org-plus-contrib nil nil))
```
Which I would recommend against. It should throw an error when trying to require the non-existent `org-plus-contrib` library.

**Comment by progfolio** [comment]
The following will work, but it doesn't inform straight about which packages are included
in the org-contrib repo.

``emacs-lisp
(use-package org-contrib
  :straight (:type git :repo "https://git.sr.ht/~bzg/org-contrib"))
```

The latest recipe we provide should take care of that:

```emacs-lisp
( org-contrib :type git
  :includes ( ob-arduino ob-clojure-literate ob-csharp ob-eukleides ob-fomus ob-julia
              ob-mathematica ob-mathomatic ob-oz ob-php ob-redis ob-sclang ob-smiles
              ob-spice ob-stata ob-tcl ob-vbnet ol-bookmark ol-elisp-symbol ol-git-link
              ol-man ol-mew ol-notmuch ol-vm ol-wl org-annotate-file org-attach-embedded-images
              org-bibtex-extras org-checklist org-choose org-collector org-contacts org-contribdir
              org-depend org-effectiveness org-eldoc org-eval org-eval-light org-expiry
              org-interactive-query org-invoice org-learn org-license org-mac-iCal
              org-mac-link org-mairix org-notify org-panel org-passwords org-registry
              org-screen org-screenshot org-secretary org-static-mathjax org-sudoku
              orgtbl-sqlinsert org-toc org-track org-velocity org-wikinodes ox-bibtex
              ox-confluence ox-deck ox-extra ox-freemind ox-groff ox-koma-letter
              ox-rss ox-s5 ox-taskjuggler)
  :repo "https://git.sr.ht/~bzg/org-contrib" :files (:defaults "lisp/*.el"))
```

**Comment by aspiers** [comment]
Haha oops, I forgot that the `plus` is redundant now.  But I didn't know straight.el has an `org-contrib` recipe hardcoded in; thanks for sharing that.  Does it need to hardcode all those includes though?  That's another thing to worry about keeping in sync; dynamic detection would be much nicer.

**Comment by progfolio** [comment]
> Does it need to hardcode all those includes though? That's another thing to worry about keeping in sync; dynamic detection would be much nicer.

That would require making a network call when requesting the recipe or pre-downloading the repository and listing its contents.
I don't think that's worth it in this case. The goal with org-contrib is for maintainers to "adopt" each package and host it elsewhere. So that list should only ever be shrinking over time and, eventually, the repository may disappear altogether.

That said, if you know you'll only ever be using a subset of those packages, you can override the `:includes` keyword's value in your init file. e.g.

```emacs-lisp
(straight-use-package '(org-plus-contrib :includes (org-sudoku))
```

You can modify that as necessary,  too.

**Comment by aspiers** [comment]
[**@progfolio**](https://github.com/progfolio) commented on [May 26, 2021 1:18 PM](https://github.com/raxod502/straight.el/issues/762#issuecomment-848721138 "2021-05-26T12:18:08Z - Replied by Github Reply Comments"):
> > Does it need to hardcode all those includes though? That's another thing to worry about keeping in sync; dynamic detection would be much nicer.
> 
> That would require making a network call when requesting the recipe or pre-downloading the repository and listing its contents.

Forgive my ignorance, but why would either of those be required?  Can't it just automatically figure out which packages are available after the git clone, through some basic wildcarding scheme?  I thought that many other recipes already do that.

**Comment by progfolio** [comment]
Currently the `:includes` keyword is parsed during `straight--register-recipe` which is called prior to cloning the repo during `straight-use-package`.

Open to alternative ideas/implementations if you think of any.

**Comment by aspiers** [comment]
OK, think I get it now - thanks a lot for the clarification!

**Comment by gagbo** [comment]
As there are more and more packages on NonGNU ELPA I'm starting to think it'd be worth it to expand the mirror to contain both GNU and NonGNU, under the assumption that both archives use the same build system.

It seems to be a quickwin, and I don't see a lot of downsides to doing so (most importantly, I don't expect any name collision since FSF oversees both archives)

**Comment by raxod502** [comment]
I started https://github.com/radian-software/gnu-elpa-mirror/pull/5, but upon looking at https://git.savannah.gnu.org/cgit/emacs/nongnu.git/tree/elpa-packages I realized that actually none of the packages in NonGNU ELPA are vendored into the repository or tracked in Emacs core, thank goodness, so actually all that is needed is a recipe repository definition in `straight.el` - no updates to GNU ELPA Mirror needed. This should be fairly straightforward although I do not have the time just at this moment.

That said, unless I'm misunderstanding, there probably isn't a huge use case for NonGNU ELPA support since all the packages are also available with the same recipes on MELPA, right?

**Comment by gagbo** [comment]
I've been exploring flymake/eglot recently, and it seems at least one developer is pushing some packages only on NonGNU ELPA:

- [corfu-terminal](https://codeberg.org/akib/emacs-corfu-terminal)
- [popon](https://codeberg.org/akib/emacs-popon) and packages depending on it like [flymake-popon](https://codeberg.org/akib/emacs-flymake-popon)

I guess it was only a question of time until either NonGNU ELPA reveals really useless or some packages are published only there when avoiding duplication. Looks like for the time being we're going towards the latter solution (extra fragmentation)

**Comment by raxod502** [comment]
Odd. Can't say I see that as the best way forward, but I certainly don't have any objection to supporting NonGNU ELPA in `straight.el` in any case. Thanks for the context on why people might benefit from the addition!

**Comment by progfolio** [comment]
Preliminary support added. I haven't done exhaustive testing, but the following test case illustrates that it works for `corfu-terminal`:


<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :user-dir "nongnu.test"
  :pre-bootstrap 
  (setq straight-repository-user "progfolio" straight-repository-branch "feat/nongnu")
  :post-bootstrap 
  (setq debug-on-error t)
  (straight-use-package 'corfu-terminal))
```
</details>

- Test run at: `2022-06-14 15:54:18`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> feat/nongnu, fork/feat/nongnu) dd4b170 2022-06-14`
- emacs-version: `GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6)
 of 2022-06-04`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> feat/nongnu, origin/feat/nongnu) dd4b170 2022-06-14
Cloning corfu-terminal...
Cloning corfu-terminal...done
Building corfu-terminal...
Building corfu-terminal → Cloning corfu...
Building corfu-terminal → Cloning corfu...done
Building corfu-terminal → Building corfu...
Building corfu-terminal → Building corfu...done
Building corfu-terminal → Cloning popon...
Building corfu-terminal → Cloning popon...done
Building corfu-terminal → Building popon...
Building corfu-terminal → Building popon...done
Building corfu-terminal...
Building corfu-terminal...done

Packages:
"straight"                n/a                  feat/nongnu dd4b170 2022-06-14
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 2710ca2d 2022-06-11
"gnu-elpa-mirror"         n/a                  master ecb802a 2022-06-10
"nongnu-elpa"             n/a                  main 7c53c3bc83 2022-06-08
"el-get"                  melpa                master bf3dba44 2022-06-02
"emacsmirror-mirror"      n/a                  master 634e620 2022-06-08
"corfu-terminal"          nongnu-elpa          master 7c5a8a1 2022-05-31
"corfu"                   gnu-elpa-mirror      master bfb0529 2022-06-14
"popon"                   nongnu-elpa          master d16cb74 2022-05-31


```
</details>

**Comment by thornjad** [comment]
On macOS 12.1 (M1) trying to clone nongnu-elpa causes an error from git

```
error: object 2699d230e3b592ae42506d7b5c969a7ac6a4593c: zeroPaddedFilemode: contains zero-padded file modes
fatal: fsck error in packed object
fatal: fetch-pack: invalid index-pack output
```

I was able to get around this by manually cloning into `straight/repos/` with

```
git clone https://git.savannah.gnu.org/git/emacs/nongnu.git nongnu-elpa --config transfer.fsckobjects=false --config receive.fsckobjects=false --config fetch.fsckobjects=false
```

There might be a better way to do this but the zero-padded file modes error is scary and I don't have the time. This is almost certainly an issue with the repo and not straight, but it causes straight to stop.

**Comment by progfolio** [comment]
> This is almost certainly an issue with the repo and not straight,

Agreed. There's not much we can do on our end.

**Comment by bcardoso** [comment]
> > Does it need to hardcode all those includes though? That's another thing to worry about keeping in sync; dynamic detection would be much nicer.
> 
> That would require making a network call when requesting the recipe or pre-downloading the repository and listing its contents. I don't think it's worth it in this case. The goal with org-contrib is for maintainers to "adopt" each package and host it elsewhere. So that list should only ever be shrinking over time and, eventually, the repository may disappear altogether.
> 
> That said, if you know you'll only ever be using a subset of those packages, you can override the `:includes` keyword's value in your init file. e.g.
> 
> ```emacs-lisp
> (straight-use-package '(org-contrib :includes (org-sudoku))
> ```
> 
> You can modify that as necessary, too.

Hi all. Current org-contrib built-in recipe still includes "ol-notmuch", which is not present in org-contrib anymore. This conflicts with loading ol-notmuch recipe by its own, as straight.el warns there are two conflicting recipes. By following the quoted suggestion above, I removed "ol-notmuch" from the org-contrib includes and managed to suppress the warning. Thanks, progfolio.

**Comment by aspiers** [comment]
> > This is almost certainly an issue with the repo and not straight,

I'm also getting the `zeroPaddedFilemode` error now.  Absolutely no idea why I wasn't before. 

> Agreed. There's not much we can do on our end.

How about adding `--config transfer.fsckobjects=false --config receive.fsckobjects=false --config fetch.fsckobjects=false` when cloning the `nongnu` repository?  If the idea of hardcoding this exception is too unsavoury, there could be a `defcustom straight-git-clone-extra-options` mapping a repository regex to a list of extra `git clone` options to use for any repository matching that regex.

**Comment by progfolio** [comment]
> If the idea of hardcoding this exception is too unsavoury, there could be a defcustom straight-vc-git-clone-extra-options mapping a repository regex to a list of extra git clone options to use for any repository matching that regex (with the above exception as a default item).

Agreed. Though, instead of mapping an alist of repo regexps to commands, I'd probably go for a simple list of options stored in a variable which could be let-bound around calls to straight-use-package. e.g.

```emacs-lisp
(let ((straight-vc-git-clone-options '("-v"))
   (straight-use-package 'etc)) 
```

**Comment by aspiers** [comment]
This would have to be done in `bootstrap.el` by wrapping the offending caller:

https://github.com/radian-software/straight.el/blob/3eca39dfc6797243ec7d1c6a7d45142407f73f88/bootstrap.el#L96-L100

**Comment by progfolio** [comment]
Correct. The general idea should still apply correctly there.
