### ISSUE TITLE
With auto-insert-mode, straight sometimes triggers interactive prompt to auto insert

### ISSUE THREAD

**Issue by darkfeline** [radian-software/straight.el#921]
## What's wrong

When `auto-insert-mode` is enabled, some actions (like `straight-rebuild-all`) pop up `auto-insert`'s interactive prompt which asks whether to insert the default Emacs Lisp template.

## Directions to reproduce

I couldn't get a reproducible example using `straight-bug-report`, but I have a stack trace that shows the problem.

```
  auto-insert()
  run-hooks(find-file-hook)
  after-find-file(t t)
  find-file-noselect-1(#<buffer straight-autoloads.el> "~/.emacs.d/straight/build/straight/straight-autolo..." nil nil "~/.emacs.d/straight/build/straight/straight-autolo..." nil)
  find-file-noselect("/home/ionasal/.emacs.d/straight/build/straight/straight-autoloads.el")
  autoload-find-generated-file()
  update-directory-autoloads("/home/ionasal/.emacs.d/straight/build/straight/")
  straight--build-autoloads((:type git :host github :repo "raxod502/straight.el" :files ("straight*.el") :branch "master" :package "straight" :local-repo "straight.el"))
  run-hook-with-args(straight--build-autoloads (:type git :host github :repo "raxod502/straight.el" :files ("straight*.el") :branch "master" :package "straight" :local-repo "straight.el"))
  straight--build-package((:type git :host github :repo "raxod502/straight.el" :files ("straight*.el") :branch "master" :package "straight" :local-repo "straight.el") nil)
  straight--transaction-exec(use-package-\"842e6298a476922be9580e91247c83a7\"-nil-nil :now #f(compiled-function () #<bytecode 0x15843053ad75>))
  straight-use-package(straight)
  straight-rebuild-all()
  funcall-interactively(straight-rebuild-all)
  call-interactively(straight-rebuild-all record nil)
  command-execute(straight-rebuild-all record)
  execute-extended-command(nil "straight-rebuild-all" nil)
  funcall-interactively(execute-extended-command nil "straight-rebuild-all" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

Basically, `autoload-find-generated-file` uses `find-file`, and if said file is new/empty, `auto-insert` triggers.

So this is an upstream bug.  I don't know if addressing such bugs is in scope for `straight.el` (since from the user experience perspective it appears to be a straight.el bug).  If not you can close this wontfix.

**Comment by progfolio** [comment]
It looks like this has been solved upstream by: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=43460
Will have a workaround for earlier Emacs versions momentarily.

**Comment by darkfeline** [comment]
It's been a while since I've seen this occur, partly due to using Emacs 28 now and also having added an advice to fix this.  I'm okay with closing this out.  Rest assured if I discover it's still broken I'll reopen.
