### ISSUE TITLE
org-contacts has disappeared

### ISSUE THREAD

**Issue by brittAnderson** [radian-software/straight.el#952]
Did an update today with emacs 28.1 and org-mode 9.5.4 using this recipe and the develop branch of straight.el

```
(straight-use-package
 '(org-plus-contrib
   :type git
   :repo "https://code.orgmode.org/bzg/org-mode.git"
   :local-repo "org"
   ;; `org-version' depends on repository tags
   :depth full
   :pre-build ("make" "autoloads")
   ;; Org's make autoloads generates org-version.el
   :build (:not autoloads)
   :files ( :defaults
            "lisp/*.el"
            ("etc/styles/" "etc/styles/*")
            "contrib/lisp/*.el")
   :includes org))

```

My start-up gave me the error that `'org-contacts` could not be found. It is not in the `org-plus-contrib` directory, but as far as I can see from the change log at orgmode.org they have not dropped it. Does anyone have any ideas?

And can I have the current recommended way to hand the split of `org`, `org-contrib`, and `org-plus-contrib`? Trying to piece it together from old issues leaves me a little uncertain if what I am doing is the most future proof way, or just something that luckily works for now. 

One solution for the `'org-contacts` issue is to grab an old version of the file and manually move it into my `plus-contrib` directory, but that is obviously just a band aid 

Thank you,

**Comment by brittAnderson** [comment]
Looks like orgmode has removed several files to their own repositories: https://git.savannah.gnu.org/cgit/emacs/nongnu.git/commit/?h=elpa/org-contrib&id=3dd98415225823f21fb7e12f272c0f199ac7407f

This will require rewriting recipes for these with their unique url found in each file. 

I am getting errors using org-contacts, but this does get the file installed to my computer. 

```
(use-package org-contacts
  :straight (org-contacts
	     :repo "https://repo.or.cz/org-contacts.git"
	     :local-repo "org-contacts")
  :config (setq org-contacts-files '("~/org/apptTodos/contacts.org")))
```

Is this the correct way to be doing things?

**Comment by progfolio** [comment]
Yes. That looks correct.

The goal of org-contrib is for all of those packages to eventually be independently maintained and hosted by interested parties. I will update our org-contrib recipe to reflect the packages removed (though it doesn't look like you're relying on straight's provided recipe anyhow, so this should not have any effect on your set-up).

**Comment by raxod502** [comment]
Sounds like the expected way to use org-contacts now is to update MELPA and run from there: https://melpa.org/#/org-contacts
