### ISSUE TITLE
Bug in `straight-vc-git--ensure-local`

### ISSUE THREAD

**Issue by usaoc** [radian-software/straight.el#955]
## What's wrong
The `upstream-branch` variable in `straight-vc-git--ensure-local` introduced in 07cedf0 can be `nil`, causing the later call to `straight-vc-git--ensure-branch-exists` to error.

## Directions to reproduce
```emacs-lisp
(straight-bug-report
  :pre-bootstrap (setq straight-repository-branch "develop")
  :post-bootstrap
  (straight-use-package 'dash)
  (toggle-debug-on-error)
  (straight-pull-package "dash"))
```

### Version information
* Emacs version: 29.0.50 (master)

**Comment by raxod502** [comment]
Fixed in https://github.com/radian-software/straight.el/commit/b6dba13aa2660e4bff5e0bae9f7e684e0497b9ab, sorry for the inconvenience.
