### ISSUE TITLE
Hangs forever on "Building org..."

### ISSUE THREAD

**Issue by rhstanton** [radian-software/straight.el#963]
## What's wrong

Starting today, straight.el clones org, but then hangs forever with "Building org..." in the minibuffer

## Directions to reproduce

Start emacs with the following init.el and an empty straight.el directory. It'll clone org, but then hang forever with "Building org" in the modeline, and no org subdirectory ever appears under "build". This worked fine until very recently:
```
(setq straight-repository-branch "develop")

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package '(org :type git :repo "https://code.orgmode.org/bzg/org-mode.git"))
```

### Version information

* Emacs version: 28.1
* Operating system: macOS 12.4

**Comment by progfolio** [comment]
Unable to reproduce:


<details open><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :post-bootstrap 
  (straight-use-package 'org))
```
</details>

- Test run at: `2022-06-18 03:00:44`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> fix/image-mode-psuedo-package, fork/fix/image-mode-psuedo-package) c799217 2022-06-16`
- emacs-version: `GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6)
 of 2022-06-16`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) 0e204d4 2022-06-16
Cloning org...
Cloning org...done
Building org...
Building org...done

Packages:
"straight"                n/a                  develop 0e204d4 2022-06-16
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master 0182b7ab 2022-06-16
"gnu-elpa-mirror"         n/a                  master ecb802a 2022-06-10
"nongnu-elpa"             n/a                  main 7c53c3bc83 2022-06-08
"el-get"                  melpa                master bf3dba44 2022-06-02
"emacsmirror-mirror"      n/a                  master 634e620 2022-06-08
"org"                     org-elpa             main 9632401dc 2022-06-18


```
</details>

The repo URL you have in that recipe is outdated, but it should redirect to the current repository.
However, I would recommend using the recipe we provide by just specifying:

```emacs-lisp
(straight-use-package 'org)
```

You can try and evaluate the test form above to see if it installs for you in a clean environment.

**Comment by yantar92** [comment]
rhstanton ***@***.***> writes:

> Starting today, straight.el clones org, but then hangs forever with "Building org..." in the minibuffer

Note that we had a slight issue with Org build recently because of
fiddling around with GC. The issue has been resolved promptly and is not
present anymore on the latest main.

Best,
Ihor

**Comment by rhstanton** [comment]
Starting from an empty ~/.emacs.d, all works fine again. Who knows what the problem was...
