### ISSUE TITLE
Steps to recover from "No catch for tag: emacs-version-changed"

### ISSUE THREAD

**Issue by jasonhemann** [radian-software/straight.el#966]
I find myself not-infrequently encountering the following error:

```
if: No catch for tag: emacs-version-changed, nil
```

As I understand it, `bootstrap.el` is supposed to catch that tag, and the `straight.el` bootstrap code should require that `bootstrap.el` is loaded. How can I determine what sequences of events are bringing me into a state when the emacs version has changed and that bootstrap code's `catch` isn't known to emacs?

**Comment by progfolio** [comment]
The reason this error is thrown is because byte-code is not guaranteed to work across Emacs versions.
byte-compiling straight.el with the version of Emacs you intend to run will fix this error.

**Comment by jasonhemann** [comment]
So, if I wanted to automatically try and do that recovery, I'd want my `init` to also catch that emacs-version-change, then try byte-compile straight.el and continue. It would only *actually* "raise an un-caught tag", so to speak, if byte-compile failed for some reason or if even after byte-compiling I reached that same error state. Something like that?

**Comment by bestlem** [comment]
See also #965 and #931

**Comment by jasonhemann** [comment]
@bestlem I may be inadvertently encountering the same friction that you are. I'm also using [Mitsuharu Yamamoto's emacs-mac](https://bitbucket.org/mituharu/emacs-mac/src/master/). I believe I do have two versions of Emacs installed on my system, the emacs standard package in homebrew and mithuraru's version as a cask (some dependency seemed to require it). I will stay tuned to that issue and see if I can separately diagnose what I'm seeing on my system.

**Comment by jasonm23** [comment]
@jasonhemann did you use/compile packages with both versions of emacs?  If not you shouldn't have any issues wrt to that.

**Comment by jasonhemann** [comment]
I certainly didn't do so deliberately. I might have accidentally, though. I'll re-open if I can reproduce.
