### ISSUE TITLE
straight-use-package returns nil when called multiple times

### ISSUE THREAD

**Issue by ivan-pop** [radian-software/straight.el#973]
## What's wrong
I have been messing up with my init file and found out that if put multiple uses of `straight-use-package` for the same package then all later ones after the first one will return nil. The same can be reproduced by simply wrapping `straight-use-package` calls in `progn` statement.

<details><summary>Test Case</summary>

```emacs-lisp
(straight-bug-report
  :post-bootstrap 
  (message "%s"
           (straight-use-package 'gcmh))
  (message "%s"
           (straight-use-package 'gcmh)))
```
</details>

- Test run at: `2022-07-08 18:26:34`
- system-type: `gnu/linux`
- straight-version: `prerelease (HEAD -> master, origin/master, origin/HEAD) af5437f 2021-09-27`
- emacs-version: `GNU Emacs 29.0.50 (build 3, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6)
 of 2022-06-26`

<details><summary>Output</summary>

```emacs-lisp
Bootstrapping straight.el...
Bootstrapping straight.el...done
Looking for gnu-elpa-mirror recipe → Cloning melpa...
Looking for gnu-elpa-mirror recipe → Cloning melpa...done
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...
Looking for nongnu-elpa recipe → Cloning gnu-elpa-mirror...done
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...
Looking for emacsmirror-mirror recipe → Cloning nongnu-elpa...done
Looking for emacsmirror-mirror recipe → Cloning el-get...
Looking for emacsmirror-mirror recipe → Cloning el-get...done
Looking for straight recipe → Cloning emacsmirror-mirror...
Looking for straight recipe → Cloning emacsmirror-mirror...done
Building straight...
Building straight...done

Test run with version: prerelease (HEAD -> develop, origin/develop) ba36462 2022-06-22
Cloning gcmh...
Cloning gcmh...done
Building gcmh...
Building gcmh...done

t
nil
Packages:
"straight"                n/a                  develop ba36462 2022-06-22
"org-elpa"                n/a                  n/a
"melpa"                   n/a                  master f1f3d4dc 2022-07-04
"gnu-elpa-mirror"         n/a                  master aa9f053 2022-06-28
"nongnu-elpa"             n/a                  main 0461407fbe 2022-07-07
"el-get"                  melpa                master bf3dba44 2022-06-02
"emacsmirror-mirror"      n/a                  master ebaa7a9 2022-06-21
"gcmh"                    melpa                master 0089f9c 2020-11-16


```
</details>

**Comment by progfolio** [comment]
This is by design.
What is the use case you're hoping for by calling `straight-use-package' multiple times for the same package?

**Comment by ivan-pop** [comment]
I was changing things in my config from declaring all packages in single place to declaring them in place they are used, and using something like `(when (straight-use-package 'foo))` was not working because I did not removed statement from the file where packages were declared initially. 
If this is by design then it's fine since it's not really that hard to fix in my config. I just though I should report it in case this is was bug. You can close this issue then

**Comment by raxod502** [comment]
Hum. While this isn't a bug in behavior, it might be a bug in documentation. This is what the docstring says:

```
Return non-nil if package was actually installed, and nil
otherwise (this can only happen if NO-CLONE is non-nil).
```

**Comment by progfolio** [comment]
>  it might be a bug in documentation

I've changed the wording of the docstring.
