### ISSUE TITLE
Change to a better mirror for savannah repos

### ISSUE THREAD

**Issue by drishal** [radian-software/straight.el#974]
I have a small question, is there a way to download say, packages from Savannah like org mode from something like https://github.com/emacs-straight/org-mode/? 
because for some reason from my region/internet, it always fails to connect to Savannah, and cloning eventually fails with `error: Failed to run "git"; see buffer *straight-process* `

EDIT: woops I accidently marked as closed

**Comment by progfolio** [comment]
>  is there a way to download say, packages from Savannah like org mode from something like https://github.com/emacs-straight/org-mode/?

Yes. The documentation for recipes covers such cases.

https://github.com/radian-software/straight.el/tree/develop#installing-with-a-custom-recipe

Note the mention of `straight-allow-recipe-inheritance`.
Org has a `:pre-build` step and some custom `:files` for its recipe. You'll likely want to inherit from the org recipe we provide with our `org-elpa` recipe repository, overriding the repo location. Something like the following should work:

```emacs-lisp
(straight-use-package '(org :host github :repo "emacs-straight/org-mode"))
```

**Comment by drishal** [comment]
reading the wiki more properly I realised I can skip the lengthy cloning process by just using the builtin version of org in emacs..I hope that does not cause issues 
```lisp
(straight-use-package '(org :type built-in))
```

**Comment by progfolio** [comment]
> eading the wiki more properly I realised I can skip the lengthy cloning process by just using the builtin version of org in emacs..I hope that does not cause issues

You'll be using the version of Org that ships with your version of Emacs. It should not cause issues unless a package requires a newer version of Org mode than the one you have installed.


> also one more small question, is there a way to add something like say, depth-1 to make cloning more quicker?

There is a `:depth` recipe keyword. Please refer to the following documentation:

https://github.com/radian-software/straight.el/tree/develop#git-backend

**Comment by drishal** [comment]
Oh ok thanks a lot for answering my queries 😅
