### ISSUE TITLE
straight-get-recipe does not list all available recipes

### ISSUE THREAD

**Issue by qwekjh** [radian-software/straight.el#976]
When interactively executing `straight-get-recipe`, there are packages (in my case, `rainbow-delimiters` and `vertico`), which do not appear as candidates.

However, the recipe files exist (I have installed both packages with `straight-use-package` without specifying a recipe, and I could find them in `straight/repos/melpa/recipes` and `straight/repos/gnu-elpa-mirror`, respectively). I also verified these results with `straight-recipe-source`.

`straight-recipes-retrieve` could find the recipes of these packages.

I barely configured `straight.el` (only changing `straight-base-dir`, and modifying the bootstrap script to reflect this change (`expand-file-name`'s second argument)).

I don't know if it is a mistake on my part, but I would like to know why this happens.

**Comment by progfolio** [comment]
> I would like to know why this happens.


`straight-get-recipe` (and `straight-use-package`, which calls it internally) will not offer package's which have previously been installed. This was a requested feature:

https://github.com/radian-software/straight.el/issues/460

You could write a command to work around that if you want to see every available package. e.g. 

```emacs-lisp
(defun +straight-get-recipe* ()
  "Like `straight-get-recipe', but offers all candidates."
  (interactive)
  (let ((straight--repo-cache (make-hash-table)))
    (call-interactively #'straight-get-recipe)))
```

**Comment by qwekjh** [comment]
I see, thank you!

**Comment by aspiers** [comment]
As mentioned in https://github.com/radian-software/straight.el/issues/1024#issuecomment-1370260650, the request in #460 only concerned `straight-use-package`, and I believe that modifying `straight-get-recipe` caused undesirable fallout for other usages of `straight-get-recipe`, as described in #1024.  So I would suggest reopening this.  In the linked comment, I propose moving the installed packages filter from `straight-get-recipe` to `straight-use-package` which would solve this reported issue whilst avoiding any regression of #460.

**Comment by raxod502** [comment]
I think that problem in particular was solved by https://github.com/radian-software/straight.el/issues/1024#issuecomment-1370366452, https://github.com/radian-software/straight.el/issues/1024#issuecomment-1370931007.
