### ISSUE TITLE
autoload.el deprecated in newest Emacs development version

### ISSUE THREAD

**Issue by andersjohansson** [radian-software/straight.el#985]
This is just a heads up that autoload.el seems to be in the process of being replaced by loaddefs-gen.el, which was introduced in the last months (starting from Emacs commit 1d4e9034178)

For straight.el this would probably involve invoking `loaddefs-generate` (introduced in loaddefs-gen.el) instead of `make-directory-autoloads` or `update-directory-autoloads` in `straight--build-autoloads`. Maybe a check for `(fboundp 'loaddefs-generate)` and calling that instead would be enough, but I am not sure whether it is a drop in replacement.

**Comment by andersjohansson** [comment]
I will try out my changes in #986.

**Comment by progfolio** [comment]
Thanks for bringing this to our attention.
Was there a discussion of this on emacs-devel? I'm curious to learn more about this change.

**Comment by andersjohansson** [comment]
I actually didn’t find anything on emacs-devel, may be in some bug report, otherwise most information I found was in the commits from Lars and notes in NEWS.

**Comment by progfolio** [comment]
Considering this closed as #986 was merged. Thanks again, @andersjohansson.
