### ISSUE TITLE
support MELPA codeberg, sourcehut :fetcher values

### ISSUE THREAD

**Issue by progfolio** [radian-software/straight.el#991]
See: https://github.com/melpa/package-build/issues/63#issuecomment-1223393528

This would involve modifying `striaght-vc-git--encode-url`, `straight-vc-git--decode-url`, `straight-recipes-melpa-retrieve`, and `straight-visit-package-website`.

**Comment by consoleaf** [comment]
Also: `straight-host-usernames`, `straight-hosts`,  `straight-vc-git-default-protocol`.
Docstrings also need updating

**Comment by leungbk** [comment]
Sourcehut also supports Mercurial in addition to Git (so https://hg.sr.ht is a possibility, in addition to the existing https://git.sr.ht); would it be better to leave this issue open till that is accounted for in Straight? @progfolio

**Comment by progfolio** [comment]
> Sourcehut also supports Mercurial in addition to Git (so https://hg.sr.ht/ is a possibility, in addition to the existing https://git.sr.ht/); would it be better to leave this issue open till that is accounted for in Straight?

Currently straight.el only supports a git vc backend. It is written so that other backends could be implemented, such as a Mercurial backend, but that has not been done. I think it's fine to leave this issue closed for now. If a Mercurial backend is implemented, this will be one of many features it would have to implement.
