### ISSUE TITLE
straight-visit-package-website to allow selecting installed packages

### ISSUE THREAD

**Issue by RuijieYu** [radian-software/straight.el#998]
I tried to view the homepage for `lispy` after having installed, but was unable to do so.

I looked into the source code under current master and found this snippet (under function `straight-get-recipe`) that directly relates to the issue I have: https://github.com/radian-software/straight.el/blob/f21103d97d180fba0b6e2e86ebb0b6269219ef2c/straight.el#L5608-L5610

Essentially, according to the code, I am unable to see `lispy` in the selection prompt because I have installed `lispy`, and `(gethash "lispy" straight--repo-cache)` returns non-`nil` (a plist).  Interestingly, I am able to see `straight` pointing to this repository as `(gethash "straight" straight--repo-cache)` returns `nil`.

Ideally, I want to still be able to visit the homepage (and its documentation) even after having installed it, so I suggest we slightly alter the functions `straight-visit-package-website` and `straight-get-recipe`, so that websites for all available packages, regardless of whether they are installed, are made available in the selection prompt.

Alternatively, we could also make this a configurable option where the user decides whether installed packages are listed in the package website command. 

I see this as a relatively small change, so I can make the PR when the feature request is accepted.

**Comment by progfolio** [comment]
>  tried to view the homepage for lispy after having installed, but was unable to do so.

Thanks for the detailed report.

> Alternatively, we could also make this a configurable option where the user decides whether installed packages are listed in the package website command.

I don't think that is necessary. Your use-case makes perfect sense. Just an oversight on my part when one of the recipe listing functions changed.

I've fixed it in #1000 which is merged to the "develop" branch.
This also allows `straight-visit-package-website` to be used programatically.

Testing is appreciated. Thanks.
